//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: config_info.proto
namespace TableProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"config_info")]
  public partial class config_info : global::ProtoBuf.IExtensible
  {
    public config_info() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _param1 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private int _param2 = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"config_info_ARRAY")]
  public partial class config_info_ARRAY : global::ProtoBuf.IExtensible
  {
    public config_info_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<TableProto.config_info> _items = new global::System.Collections.Generic.List<TableProto.config_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TableProto.config_info> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}