//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: systemaddress.proto
namespace TableProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"systemaddress")]
  public partial class systemaddress : global::ProtoBuf.IExtensible
  {
    public systemaddress() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _showName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"showName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string showName
    {
      get { return _showName; }
      set { _showName = value; }
    }
    private string _clientEnum = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"clientEnum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clientEnum
    {
      get { return _clientEnum; }
      set { _clientEnum = value; }
    }
    private string _sysIcon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sysIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sysIcon
    {
      get { return _sysIcon; }
      set { _sysIcon = value; }
    }
    private int _bindActivityId = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bindActivityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int bindActivityId
    {
      get { return _bindActivityId; }
      set { _bindActivityId = value; }
    }
    private bool _isShow = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isShow
    {
      get { return _isShow; }
      set { _isShow = value; }
    }
    private int _require_lvl = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"require_lvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int require_lvl
    {
      get { return _require_lvl; }
      set { _require_lvl = value; }
    }
    private int _require_quest = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"require_quest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int require_quest
    {
      get { return _require_quest; }
      set { _require_quest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"systemaddress_ARRAY")]
  public partial class systemaddress_ARRAY : global::ProtoBuf.IExtensible
  {
    public systemaddress_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<TableProto.systemaddress> _items = new global::System.Collections.Generic.List<TableProto.systemaddress>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TableProto.systemaddress> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}