# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config_info.proto',
  package='TableProto',
  serialized_pb='\n\x11\x63onfig_info.proto\x12\nTableProto\"A\n\x0b\x63onfig_info\x12\r\n\x02ID\x18\x01 \x02(\x05:\x01\x30\x12\x10\n\x06param1\x18\x02 \x01(\t:\x00\x12\x11\n\x06param2\x18\x03 \x01(\x05:\x01\x30\";\n\x11\x63onfig_info_ARRAY\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.TableProto.config_info')




_CONFIG_INFO = _descriptor.Descriptor(
  name='config_info',
  full_name='TableProto.config_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='TableProto.config_info.ID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param1', full_name='TableProto.config_info.param1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param2', full_name='TableProto.config_info.param2', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=98,
)


_CONFIG_INFO_ARRAY = _descriptor.Descriptor(
  name='config_info_ARRAY',
  full_name='TableProto.config_info_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='TableProto.config_info_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=100,
  serialized_end=159,
)

_CONFIG_INFO_ARRAY.fields_by_name['items'].message_type = _CONFIG_INFO
DESCRIPTOR.message_types_by_name['config_info'] = _CONFIG_INFO
DESCRIPTOR.message_types_by_name['config_info_ARRAY'] = _CONFIG_INFO_ARRAY

class config_info(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONFIG_INFO

  # @@protoc_insertion_point(class_scope:TableProto.config_info)

class config_info_ARRAY(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONFIG_INFO_ARRAY

  # @@protoc_insertion_point(class_scope:TableProto.config_info_ARRAY)


# @@protoc_insertion_point(module_scope)
