# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemaddress.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='systemaddress.proto',
  package='TableProto',
  serialized_pb='\n\x13systemaddress.proto\x12\nTableProto\"\xb8\x01\n\rsystemaddress\x12\r\n\x02ID\x18\x01 \x02(\x05:\x01\x30\x12\x12\n\x08showName\x18\x02 \x01(\t:\x00\x12\x14\n\nclientEnum\x18\x03 \x01(\t:\x00\x12\x11\n\x07sysIcon\x18\x04 \x01(\t:\x00\x12\x19\n\x0e\x62indActivityId\x18\x05 \x01(\x05:\x01\x30\x12\x0e\n\x06isShow\x18\x06 \x01(\x08\x12\x16\n\x0brequire_lvl\x18\x07 \x01(\x05:\x01\x30\x12\x18\n\rrequire_quest\x18\x08 \x01(\x05:\x01\x30\"?\n\x13systemaddress_ARRAY\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.TableProto.systemaddress')




_SYSTEMADDRESS = _descriptor.Descriptor(
  name='systemaddress',
  full_name='TableProto.systemaddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='TableProto.systemaddress.ID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='showName', full_name='TableProto.systemaddress.showName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientEnum', full_name='TableProto.systemaddress.clientEnum', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sysIcon', full_name='TableProto.systemaddress.sysIcon', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bindActivityId', full_name='TableProto.systemaddress.bindActivityId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isShow', full_name='TableProto.systemaddress.isShow', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='require_lvl', full_name='TableProto.systemaddress.require_lvl', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='require_quest', full_name='TableProto.systemaddress.require_quest', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=220,
)


_SYSTEMADDRESS_ARRAY = _descriptor.Descriptor(
  name='systemaddress_ARRAY',
  full_name='TableProto.systemaddress_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='TableProto.systemaddress_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=222,
  serialized_end=285,
)

_SYSTEMADDRESS_ARRAY.fields_by_name['items'].message_type = _SYSTEMADDRESS
DESCRIPTOR.message_types_by_name['systemaddress'] = _SYSTEMADDRESS
DESCRIPTOR.message_types_by_name['systemaddress_ARRAY'] = _SYSTEMADDRESS_ARRAY

class systemaddress(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYSTEMADDRESS

  # @@protoc_insertion_point(class_scope:TableProto.systemaddress)

class systemaddress_ARRAY(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYSTEMADDRESS_ARRAY

  # @@protoc_insertion_point(class_scope:TableProto.systemaddress_ARRAY)


# @@protoc_insertion_point(module_scope)
