//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LActionDataRoot.proto
// Note: requires additional types generated from: OneActionData.proto
// Note: requires additional types generated from: LTimeEventProType.proto
// Note: requires additional types generated from: LHitDataInput.proto
// Note: requires additional types generated from: LCharacterModelData.proto
// Note: requires additional types generated from: LProjectileModelData.proto
// Note: requires additional types generated from: LEvaluationData.proto
// Note: requires additional types generated from: MoveTestData.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LActionDataRoot")]
  public partial class LActionDataRoot : global::ProtoBuf.IExtensible
  {
    public LActionDataRoot() {}
    
    private readonly global::System.Collections.Generic.List<ActionData.OneActionData> _oneActionDataList = new global::System.Collections.Generic.List<ActionData.OneActionData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"oneActionDataList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.OneActionData> oneActionDataList
    {
      get { return _oneActionDataList; }
    }
  
    private string _NowTestActionName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NowTestActionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string NowTestActionName
    {
      get { return _NowTestActionName; }
      set { _NowTestActionName = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _fmodBankList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"fmodBankList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> fmodBankList
    {
      get { return _fmodBankList; }
    }
  
    private bool _debugMode = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"debugMode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool debugMode
    {
      get { return _debugMode; }
      set { _debugMode = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LHitDataInput> _hitDataList = new global::System.Collections.Generic.List<ActionData.LHitDataInput>();
    [global::ProtoBuf.ProtoMember(6, Name=@"hitDataList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LHitDataInput> hitDataList
    {
      get { return _hitDataList; }
    }
  
    private ActionData.LCharacterModelData _characterModelData = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"characterModelData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LCharacterModelData characterModelData
    {
      get { return _characterModelData; }
      set { _characterModelData = value; }
    }
    private ActionData.LProjectileModelData _projectileModelData = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"projectileModelData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LProjectileModelData projectileModelData
    {
      get { return _projectileModelData; }
      set { _projectileModelData = value; }
    }
    private ActionData.LEvaluationData _evaluationData = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"evaluationData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LEvaluationData evaluationData
    {
      get { return _evaluationData; }
      set { _evaluationData = value; }
    }
    private ActionData.MoveTestData _moveTestData = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"moveTestData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.MoveTestData moveTestData
    {
      get { return _moveTestData; }
      set { _moveTestData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}