//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LAddColorSeparation.proto
// Note: requires additional types generated from: LTimeEventProType.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LAddColorSeparation")]
  public partial class LAddColorSeparation : global::ProtoBuf.IExtensible
  {
    public LAddColorSeparation() {}
    
    private float _startStrength = (float)2;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"startStrength", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)2)]
    public float startStrength
    {
      get { return _startStrength; }
      set { _startStrength = value; }
    }
    private float _endStrength = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endStrength", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float endStrength
    {
      get { return _endStrength; }
      set { _endStrength = value; }
    }
    private float _startResolutionl = (float)0.01;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"startResolutionl", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0.01)]
    public float startResolutionl
    {
      get { return _startResolutionl; }
      set { _startResolutionl = value; }
    }
    private float _endResolutionl = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endResolutionl", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float endResolutionl
    {
      get { return _endResolutionl; }
      set { _endResolutionl = value; }
    }
    private float _startAngle = (float)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"startAngle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float startAngle
    {
      get { return _startAngle; }
      set { _startAngle = value; }
    }
    private float _endAngle = (float)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"endAngle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float endAngle
    {
      get { return _endAngle; }
      set { _endAngle = value; }
    }
    private float _time = (float)0.2;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0.2)]
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(101, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}