//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LAddRadialblur.proto
// Note: requires additional types generated from: LTimeEventProType.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LAddRadialblur")]
  public partial class LAddRadialblur : global::ProtoBuf.IExtensible
  {
    public LAddRadialblur() {}
    
    private ActionData.LVector3 _offset = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"offset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 offset
    {
      get { return _offset; }
      set { _offset = value; }
    }
    private float _startStrength = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"startStrength", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float startStrength
    {
      get { return _startStrength; }
      set { _startStrength = value; }
    }
    private float _endStrength = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endStrength", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float endStrength
    {
      get { return _endStrength; }
      set { _endStrength = value; }
    }
    private float _startStepScale = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"startStepScale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float startStepScale
    {
      get { return _startStepScale; }
      set { _startStepScale = value; }
    }
    private float _endStepScale = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endStepScale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float endStepScale
    {
      get { return _endStepScale; }
      set { _endStepScale = value; }
    }
    private float _startInward = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"startInward", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float startInward
    {
      get { return _startInward; }
      set { _startInward = value; }
    }
    private float _endInward = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"endInward", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float endInward
    {
      get { return _endInward; }
      set { _endInward = value; }
    }
    private float _startOutward = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"startOutward", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float startOutward
    {
      get { return _startOutward; }
      set { _startOutward = value; }
    }
    private float _endOutward = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"endOutward", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float endOutward
    {
      get { return _endOutward; }
      set { _endOutward = value; }
    }
    private float _time = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(101, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}