//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LAddBlur.proto
// Note: requires additional types generated from: LTimeEventProType.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LAddBlur")]
  public partial class LAddBlur : global::ProtoBuf.IExtensible
  {
    public LAddBlur() {}
    
    private float _interval;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"interval", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float interval
    {
      get { return _interval; }
      set { _interval = value; }
    }
    private float _life;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"life", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float life
    {
      get { return _life; }
      set { _life = value; }
    }
    private ActionData.LVector3 _mainColor = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mainColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 mainColor
    {
      get { return _mainColor; }
      set { _mainColor = value; }
    }
    private ActionData.LVector3 _blendColor = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"blendColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 blendColor
    {
      get { return _blendColor; }
      set { _blendColor = value; }
    }
    private ActionData.LVector3 _addColor = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"addColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 addColor
    {
      get { return _addColor; }
      set { _addColor = value; }
    }
    private float _startAlpha = (float)0.7;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"startAlpha", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0.7)]
    public float startAlpha
    {
      get { return _startAlpha; }
      set { _startAlpha = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(100, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"BlendMode")]
    public enum BlendMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD", Value=0)]
      ADD = 0
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Shader")]
    public enum Shader
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENT", Value=0)]
      CURRENT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENEMY", Value=1)]
      ENEMY = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}