//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LAddEffect.proto
// Note: requires additional types generated from: LTimeEventProType.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LAddEffect")]
  public partial class LAddEffect : global::ProtoBuf.IExtensible
  {
    public LAddEffect() {}
    
    private string _effectName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"effectName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string effectName
    {
      get { return _effectName; }
      set { _effectName = value; }
    }
    private string _extendEffect = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"extendEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extendEffect
    {
      get { return _extendEffect; }
      set { _extendEffect = value; }
    }
    private float _speedOffset = (float)0;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"speedOffset", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float speedOffset
    {
      get { return _speedOffset; }
      set { _speedOffset = value; }
    }
    private string _effectName_Blue = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"effectName_Blue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string effectName_Blue
    {
      get { return _effectName_Blue; }
      set { _effectName_Blue = value; }
    }
    private string _effectName_Red = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"effectName_Red", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string effectName_Red
    {
      get { return _effectName_Red; }
      set { _effectName_Red = value; }
    }
    private bool _forceAdd = default(bool);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"forceAdd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool forceAdd
    {
      get { return _forceAdd; }
      set { _forceAdd = value; }
    }
    private ActionData.LVector3 _position = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private bool _placeToFoothol = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"placeToFoothol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool placeToFoothol
    {
      get { return _placeToFoothol; }
      set { _placeToFoothol = value; }
    }
    private ActionData.LAddEffect.ScaleMode _scaleMode = ActionData.LAddEffect.ScaleMode.MODEL;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"scaleMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LAddEffect.ScaleMode.MODEL)]
    public ActionData.LAddEffect.ScaleMode scaleMode
    {
      get { return _scaleMode; }
      set { _scaleMode = value; }
    }
    private ActionData.LVector3 _scale = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private bool _scaleWithSkill = default(bool);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"scaleWithSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool scaleWithSkill
    {
      get { return _scaleWithSkill; }
      set { _scaleWithSkill = value; }
    }
    private ActionData.LVector3 _rotation = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private bool _destroyWithDead = default(bool);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"destroyWithDead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool destroyWithDead
    {
      get { return _destroyWithDead; }
      set { _destroyWithDead = value; }
    }
    private bool _isBindPosition = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isBindPosition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBindPosition
    {
      get { return _isBindPosition; }
      set { _isBindPosition = value; }
    }
    private bool _isBindFrame = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"isBindFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBindFrame
    {
      get { return _isBindFrame; }
      set { _isBindFrame = value; }
    }
    private bool _isBindAction = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isBindAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBindAction
    {
      get { return _isBindAction; }
      set { _isBindAction = value; }
    }
    private bool _isBindDirection = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"isBindDirection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBindDirection
    {
      get { return _isBindDirection; }
      set { _isBindDirection = value; }
    }
    private bool _isBindFrameWithoutSpeed = default(bool);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"isBindFrameWithoutSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBindFrameWithoutSpeed
    {
      get { return _isBindFrameWithoutSpeed; }
      set { _isBindFrameWithoutSpeed = value; }
    }
    private bool _startRotationByParent = default(bool);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"startRotationByParent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool startRotationByParent
    {
      get { return _startRotationByParent; }
      set { _startRotationByParent = value; }
    }
    private bool _untilHurt = default(bool);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"untilHurt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool untilHurt
    {
      get { return _untilHurt; }
      set { _untilHurt = value; }
    }
    private bool _bindBone = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"bindBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bindBone
    {
      get { return _bindBone; }
      set { _bindBone = value; }
    }
    private string _bindName = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"bindName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bindName
    {
      get { return _bindName; }
      set { _bindName = value; }
    }
    private bool _overrideLifeTime = (bool)false;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"overrideLifeTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool overrideLifeTime
    {
      get { return _overrideLifeTime; }
      set { _overrideLifeTime = value; }
    }
    private float _LifeTime = default(float);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"LifeTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float LifeTime
    {
      get { return _LifeTime; }
      set { _LifeTime = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ScaleMode")]
    public enum ScaleMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODEL", Value=0)]
      MODEL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLLIDER", Value=1)]
      COLLIDER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELF", Value=2)]
      SELF = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}