//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LAddCustomProjectile.proto
// Note: requires additional types generated from: LTimeEventProType.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LAddCustomProjectile")]
  public partial class LAddCustomProjectile : global::ProtoBuf.IExtensible
  {
    public LAddCustomProjectile() {}
    
    private string _prefabName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"prefabName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prefabName
    {
      get { return _prefabName; }
      set { _prefabName = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _effectList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"effectList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> effectList
    {
      get { return _effectList; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _projectileList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"projectileList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> projectileList
    {
      get { return _projectileList; }
    }
  
    private string _className = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"className", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string className
    {
      get { return _className; }
      set { _className = value; }
    }
    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private float _scale = (float)1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private ActionData.LVector3 _position = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private bool _placeToFoothol = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"placeToFoothol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool placeToFoothol
    {
      get { return _placeToFoothol; }
      set { _placeToFoothol = value; }
    }
    private ActionData.LVector3 _startAngle = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"startAngle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 startAngle
    {
      get { return _startAngle; }
      set { _startAngle = value; }
    }
    private ActionData.LVector3 _randomAngleRange = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"randomAngleRange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 randomAngleRange
    {
      get { return _randomAngleRange; }
      set { _randomAngleRange = value; }
    }
    private float _startSpeed = (float)5;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"startSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)5)]
    public float startSpeed
    {
      get { return _startSpeed; }
      set { _startSpeed = value; }
    }
    private float _acceleration = (float)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"acceleration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float acceleration
    {
      get { return _acceleration; }
      set { _acceleration = value; }
    }
    private ActionData.LVector3 _fieldForce = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"fieldForce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 fieldForce
    {
      get { return _fieldForce; }
      set { _fieldForce = value; }
    }
    private ActionData.LAddCustomProjectile.Camp _camp = ActionData.LAddCustomProjectile.Camp.CURRENT_CAMP;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LAddCustomProjectile.Camp.CURRENT_CAMP)]
    public ActionData.LAddCustomProjectile.Camp camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private bool _bindBone = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"bindBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bindBone
    {
      get { return _bindBone; }
      set { _bindBone = value; }
    }
    private string _bindName = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"bindName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bindName
    {
      get { return _bindName; }
      set { _bindName = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Camp")]
    public enum Camp
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENT_CAMP", Value=0)]
      CURRENT_CAMP = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVERSE_CAMP", Value=1)]
      INVERSE_CAMP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEUTRAL_CAMP", Value=2)]
      NEUTRAL_CAMP = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}