//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LAddPhantom.proto
// Note: requires additional types generated from: LTimeEventProType.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LAddPhantom")]
  public partial class LAddPhantom : global::ProtoBuf.IExtensible
  {
    public LAddPhantom() {}
    
    private ActionData.LVector3 _position = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private bool _placeToFoothol = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"placeToFoothol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool placeToFoothol
    {
      get { return _placeToFoothol; }
      set { _placeToFoothol = value; }
    }
    private string _actionName;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"actionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string actionName
    {
      get { return _actionName; }
      set { _actionName = value; }
    }
    private bool _reset = (bool)true;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"reset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool reset
    {
      get { return _reset; }
      set { _reset = value; }
    }
    private int _startFrame = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"startFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startFrame
    {
      get { return _startFrame; }
      set { _startFrame = value; }
    }
    private bool _checkSkill = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"checkSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkSkill
    {
      get { return _checkSkill; }
      set { _checkSkill = value; }
    }
    private bool _checkCancelPriority = default(bool);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"checkCancelPriority", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkCancelPriority
    {
      get { return _checkCancelPriority; }
      set { _checkCancelPriority = value; }
    }
    private bool _destroyOnFall = (bool)false;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"destroyOnFall", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool destroyOnFall
    {
      get { return _destroyOnFall; }
      set { _destroyOnFall = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(100, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}