//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LAutoMove.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LAutoMove")]
  public partial class LAutoMove : global::ProtoBuf.IExtensible
  {
    public LAutoMove() {}
    
    private float _speedX = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"speedX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float speedX
    {
      get { return _speedX; }
      set { _speedX = value; }
    }
    private float _speedY = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"speedY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float speedY
    {
      get { return _speedY; }
      set { _speedY = value; }
    }
    private float _speedZ = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"speedZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float speedZ
    {
      get { return _speedZ; }
      set { _speedZ = value; }
    }
    private float _accelerationX = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"accelerationX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float accelerationX
    {
      get { return _accelerationX; }
      set { _accelerationX = value; }
    }
    private float _accelerationY = (float)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"accelerationY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float accelerationY
    {
      get { return _accelerationY; }
      set { _accelerationY = value; }
    }
    private float _accelerationZ = (float)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"accelerationZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float accelerationZ
    {
      get { return _accelerationZ; }
      set { _accelerationZ = value; }
    }
    private float _randomX = (float)0;
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"randomX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float randomX
    {
      get { return _randomX; }
      set { _randomX = value; }
    }
    private float _randomY = (float)0;
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"randomY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float randomY
    {
      get { return _randomY; }
      set { _randomY = value; }
    }
    private float _randomZ = (float)0;
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"randomZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float randomZ
    {
      get { return _randomZ; }
      set { _randomZ = value; }
    }
    private float _rate = (float)1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float rate
    {
      get { return _rate; }
      set { _rate = value; }
    }
    private bool _useSpeedRate = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"useSpeedRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool useSpeedRate
    {
      get { return _useSpeedRate; }
      set { _useSpeedRate = value; }
    }
    private bool _isBodyMove = default(bool);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"isBodyMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBodyMove
    {
      get { return _isBodyMove; }
      set { _isBodyMove = value; }
    }
    private ActionData.LAutoMove.MoveType _moveType = ActionData.LAutoMove.MoveType.DEFAULT;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"moveType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LAutoMove.MoveType.DEFAULT)]
    public ActionData.LAutoMove.MoveType moveType
    {
      get { return _moveType; }
      set { _moveType = value; }
    }
    private float _trackingRate = (float)0;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"trackingRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float trackingRate
    {
      get { return _trackingRate; }
      set { _trackingRate = value; }
    }
    private bool _fly = (bool)false;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"fly", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool fly
    {
      get { return _fly; }
      set { _fly = value; }
    }
    private bool _faceToTarget = default(bool);
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"faceToTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool faceToTarget
    {
      get { return _faceToTarget; }
      set { _faceToTarget = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MoveType")]
    public enum MoveType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEFAULT", Value=0)]
      DEFAULT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOLLOW", Value=1)]
      FOLLOW = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}