//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LChangeDirectionByKeyState.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LChangeDirectionByKeyState")]
  public partial class LChangeDirectionByKeyState : global::ProtoBuf.IExtensible
  {
    public LChangeDirectionByKeyState() {}
    
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private bool _syn = default(bool);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"syn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool syn
    {
      get { return _syn; }
      set { _syn = value; }
    }
    private bool _reverse;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reverse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool reverse
    {
      get { return _reverse; }
      set { _reverse = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}