//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LChangeActionSpeed.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LChangeActionSpeed")]
  public partial class LChangeActionSpeed : global::ProtoBuf.IExtensible
  {
    public LChangeActionSpeed() {}
    
    private ActionData.LChangeActionSpeed.SpeedMode _speedMode = ActionData.LChangeActionSpeed.SpeedMode.OFFSET;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"speedMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LChangeActionSpeed.SpeedMode.OFFSET)]
    public ActionData.LChangeActionSpeed.SpeedMode speedMode
    {
      get { return _speedMode; }
      set { _speedMode = value; }
    }
    private float _speed = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private bool _setAbsoluteSpeed = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"setAbsoluteSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool setAbsoluteSpeed
    {
      get { return _setAbsoluteSpeed; }
      set { _setAbsoluteSpeed = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SpeedMode")]
    public enum SpeedMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OFFSET", Value=0)]
      OFFSET = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATIO", Value=1)]
      RATIO = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}