//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LCharacterModelData.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LCharacterModelData")]
  public partial class LCharacterModelData : global::ProtoBuf.IExtensible
  {
    public LCharacterModelData() {}
    
    private float _gravityRate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gravityRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float gravityRate
    {
      get { return _gravityRate; }
      set { _gravityRate = value; }
    }
    private float _lieTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lieTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float lieTime
    {
      get { return _lieTime; }
      set { _lieTime = value; }
    }
    private float _lieTimeRate;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lieTimeRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float lieTimeRate
    {
      get { return _lieTimeRate; }
      set { _lieTimeRate = value; }
    }
    private int _movePoint;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"movePoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int movePoint
    {
      get { return _movePoint; }
      set { _movePoint = value; }
    }
    private float _moveSpeedRate;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"moveSpeedRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float moveSpeedRate
    {
      get { return _moveSpeedRate; }
      set { _moveSpeedRate = value; }
    }
    private float _attackSpeedRate;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"attackSpeedRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float attackSpeedRate
    {
      get { return _attackSpeedRate; }
      set { _attackSpeedRate = value; }
    }
    private float _spellSpeedRate;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"spellSpeedRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float spellSpeedRate
    {
      get { return _spellSpeedRate; }
      set { _spellSpeedRate = value; }
    }
    private int _height;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private float _weight;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"weight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float weight
    {
      get { return _weight; }
      set { _weight = value; }
    }
    private float _jumpPower;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"jumpPower", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float jumpPower
    {
      get { return _jumpPower; }
      set { _jumpPower = value; }
    }
    private float _jumpPowerRate;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"jumpPowerRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float jumpPowerRate
    {
      get { return _jumpPowerRate; }
      set { _jumpPowerRate = value; }
    }
    private float _scale;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private float _flyingHeight;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"flyingHeight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float flyingHeight
    {
      get { return _flyingHeight; }
      set { _flyingHeight = value; }
    }
    private bool _modifyAvaterRotation;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"modifyAvaterRotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool modifyAvaterRotation
    {
      get { return _modifyAvaterRotation; }
      set { _modifyAvaterRotation = value; }
    }
    private bool _reverseBody = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"reverseBody", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool reverseBody
    {
      get { return _reverseBody; }
      set { _reverseBody = value; }
    }
    private bool _immunityKnock = default(bool);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"immunityKnock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool immunityKnock
    {
      get { return _immunityKnock; }
      set { _immunityKnock = value; }
    }
    private ActionData.LVector3 _colliderCenter = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"colliderCenter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 colliderCenter
    {
      get { return _colliderCenter; }
      set { _colliderCenter = value; }
    }
    private ActionData.LVector3 _colliderSize = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"colliderSize", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 colliderSize
    {
      get { return _colliderSize; }
      set { _colliderSize = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LVector3> _barrierBoxCenters = new global::System.Collections.Generic.List<ActionData.LVector3>();
    [global::ProtoBuf.ProtoMember(22, Name=@"barrierBoxCenters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LVector3> barrierBoxCenters
    {
      get { return _barrierBoxCenters; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LVector3> _barrierBoxSize = new global::System.Collections.Generic.List<ActionData.LVector3>();
    [global::ProtoBuf.ProtoMember(23, Name=@"barrierBoxSize", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LVector3> barrierBoxSize
    {
      get { return _barrierBoxSize; }
    }
  
    private ActionData.LVector3 _rotation = null;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private bool _isFlying;
    [global::ProtoBuf.ProtoMember(51, IsRequired = true, Name=@"isFlying", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFlying
    {
      get { return _isFlying; }
      set { _isFlying = value; }
    }
    private bool _isVoidBody;
    [global::ProtoBuf.ProtoMember(52, IsRequired = true, Name=@"isVoidBody", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isVoidBody
    {
      get { return _isVoidBody; }
      set { _isVoidBody = value; }
    }
    private bool _isBuilding;
    [global::ProtoBuf.ProtoMember(53, IsRequired = true, Name=@"isBuilding", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isBuilding
    {
      get { return _isBuilding; }
      set { _isBuilding = value; }
    }
    private bool _isBarrier;
    [global::ProtoBuf.ProtoMember(54, IsRequired = true, Name=@"isBarrier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isBarrier
    {
      get { return _isBarrier; }
      set { _isBarrier = value; }
    }
    private bool _isSingleSidedBarrier = (bool)false;
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"isSingleSidedBarrier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool isSingleSidedBarrier
    {
      get { return _isSingleSidedBarrier; }
      set { _isSingleSidedBarrier = value; }
    }
    private bool _isSetVolumeByDistance;
    [global::ProtoBuf.ProtoMember(57, IsRequired = true, Name=@"isSetVolumeByDistance", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isSetVolumeByDistance
    {
      get { return _isSetVolumeByDistance; }
      set { _isSetVolumeByDistance = value; }
    }
    private bool _excludingTarget;
    [global::ProtoBuf.ProtoMember(56, IsRequired = true, Name=@"excludingTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool excludingTarget
    {
      get { return _excludingTarget; }
      set { _excludingTarget = value; }
    }
    private string _layer = "";
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"layer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string layer
    {
      get { return _layer; }
      set { _layer = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LCharacterModelData.LSubCharacterData> _subCharacterList = new global::System.Collections.Generic.List<ActionData.LCharacterModelData.LSubCharacterData>();
    [global::ProtoBuf.ProtoMember(61, Name=@"subCharacterList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCharacterModelData.LSubCharacterData> subCharacterList
    {
      get { return _subCharacterList; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LCharacterModelData.LStanceData> _stanceDataList = new global::System.Collections.Generic.List<ActionData.LCharacterModelData.LStanceData>();
    [global::ProtoBuf.ProtoMember(62, Name=@"stanceDataList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCharacterModelData.LStanceData> stanceDataList
    {
      get { return _stanceDataList; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LCharacterModelData.LComboLinkData> _comboLinkDatas = new global::System.Collections.Generic.List<ActionData.LCharacterModelData.LComboLinkData>();
    [global::ProtoBuf.ProtoMember(63, Name=@"comboLinkDatas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCharacterModelData.LComboLinkData> comboLinkDatas
    {
      get { return _comboLinkDatas; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LSubCharacterData")]
  public partial class LSubCharacterData : global::ProtoBuf.IExtensible
  {
    public LSubCharacterData() {}
    
    private string _modelName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"modelName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string modelName
    {
      get { return _modelName; }
      set { _modelName = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LCharacterModelData.LSubCharacterLinkerData> _links = new global::System.Collections.Generic.List<ActionData.LCharacterModelData.LSubCharacterLinkerData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"links", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCharacterModelData.LSubCharacterLinkerData> links
    {
      get { return _links; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LSubCharacterLinkerData")]
  public partial class LSubCharacterLinkerData : global::ProtoBuf.IExtensible
  {
    public LSubCharacterLinkerData() {}
    
    private ActionData.LCharacterModelData.CharacterGroupLinkerType _linkType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"linkType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ActionData.LCharacterModelData.CharacterGroupLinkerType linkType
    {
      get { return _linkType; }
      set { _linkType = value; }
    }
    private ActionData.LVector3 _offset = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"offset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 offset
    {
      get { return _offset; }
      set { _offset = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LStanceData")]
  public partial class LStanceData : global::ProtoBuf.IExtensible
  {
    public LStanceData() {}
    
    private string _stanceName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stanceName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string stanceName
    {
      get { return _stanceName; }
      set { _stanceName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LComboLinkData")]
  public partial class LComboLinkData : global::ProtoBuf.IExtensible
  {
    public LComboLinkData() {}
    
    private string _combo = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"combo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string combo
    {
      get { return _combo; }
      set { _combo = value; }
    }
    private string _groundAction = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"groundAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string groundAction
    {
      get { return _groundAction; }
      set { _groundAction = value; }
    }
    private string _airAction = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"airAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string airAction
    {
      get { return _airAction; }
      set { _airAction = value; }
    }
    private int _priority = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int priority
    {
      get { return _priority; }
      set { _priority = value; }
    }
    private int _extendFrame = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"extendFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int extendFrame
    {
      get { return _extendFrame; }
      set { _extendFrame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CharacterGroupLinkerType")]
    public enum CharacterGroupLinkerType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POSITION", Value=1)]
      POSITION = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTION", Value=2)]
      ACTION = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOLLOW", Value=3)]
      FOLLOW = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_NODE", Value=4)]
      SKILL_NODE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=9999)]
      ALL = 9999
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}