//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LConditionsLinkerDuration.proto
// Note: requires additional types generated from: LCheckValueData.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LConditionsLinkerDuration")]
  public partial class LConditionsLinkerDuration : global::ProtoBuf.IExtensible
  {
    public LConditionsLinkerDuration() {}
    
    private bool _isContinuous = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"isContinuous", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isContinuous
    {
      get { return _isContinuous; }
      set { _isContinuous = value; }
    }
    private bool _checkSkillLevel = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"checkSkillLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkSkillLevel
    {
      get { return _checkSkillLevel; }
      set { _checkSkillLevel = value; }
    }
    private int _skillID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillID
    {
      get { return _skillID; }
      set { _skillID = value; }
    }
    private int _skillLevel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"skillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillLevel
    {
      get { return _skillLevel; }
      set { _skillLevel = value; }
    }
    private bool _checkActionTime = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"checkActionTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkActionTime
    {
      get { return _checkActionTime; }
      set { _checkActionTime = value; }
    }
    private ActionData.LConditionsLinkerDuration.CompareType _compareType = ActionData.LConditionsLinkerDuration.CompareType.MORE_THAN_TIME;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"compareType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LConditionsLinkerDuration.CompareType.MORE_THAN_TIME)]
    public ActionData.LConditionsLinkerDuration.CompareType compareType
    {
      get { return _compareType; }
      set { _compareType = value; }
    }
    private float _actionTime = (float)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"actionTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float actionTime
    {
      get { return _actionTime; }
      set { _actionTime = value; }
    }
    private ActionData.LConditionsLinkerDuration.SceneBlockHittest _sceneBlockHittest = ActionData.LConditionsLinkerDuration.SceneBlockHittest.NEVER;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sceneBlockHittest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LConditionsLinkerDuration.SceneBlockHittest.NEVER)]
    public ActionData.LConditionsLinkerDuration.SceneBlockHittest sceneBlockHittest
    {
      get { return _sceneBlockHittest; }
      set { _sceneBlockHittest = value; }
    }
    private int _checkHittedID = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"checkHittedID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int checkHittedID
    {
      get { return _checkHittedID; }
      set { _checkHittedID = value; }
    }
    private ActionData.LConditionsLinkerDuration.HittedTargetType _targetType = ActionData.LConditionsLinkerDuration.HittedTargetType.ALL_TARGET;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"targetType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LConditionsLinkerDuration.HittedTargetType.ALL_TARGET)]
    public ActionData.LConditionsLinkerDuration.HittedTargetType targetType
    {
      get { return _targetType; }
      set { _targetType = value; }
    }
    private ActionData.LConditionsLinkerDuration.CampType _hittedCampType = ActionData.LConditionsLinkerDuration.CampType.ALL_CAMP;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"hittedCampType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LConditionsLinkerDuration.CampType.ALL_CAMP)]
    public ActionData.LConditionsLinkerDuration.CampType hittedCampType
    {
      get { return _hittedCampType; }
      set { _hittedCampType = value; }
    }
    private bool _checkAccept = default(bool);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"checkAccept", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkAccept
    {
      get { return _checkAccept; }
      set { _checkAccept = value; }
    }
    private ActionData.LConditionsLinkerDuration.AcceptDirection _acceptDirection = ActionData.LConditionsLinkerDuration.AcceptDirection.ALL;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"acceptDirection", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LConditionsLinkerDuration.AcceptDirection.ALL)]
    public ActionData.LConditionsLinkerDuration.AcceptDirection acceptDirection
    {
      get { return _acceptDirection; }
      set { _acceptDirection = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LCheckValueData> _checkValue = new global::System.Collections.Generic.List<ActionData.LCheckValueData>();
    [global::ProtoBuf.ProtoMember(16, Name=@"checkValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCheckValueData> checkValue
    {
      get { return _checkValue; }
    }
  
    private bool _checkHasTarget = default(bool);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"checkHasTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkHasTarget
    {
      get { return _checkHasTarget; }
      set { _checkHasTarget = value; }
    }
    private ActionData.LConditionsLinkerDuration.CampType _targetCampType = ActionData.LConditionsLinkerDuration.CampType.ALL_CAMP;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"targetCampType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LConditionsLinkerDuration.CampType.ALL_CAMP)]
    public ActionData.LConditionsLinkerDuration.CampType targetCampType
    {
      get { return _targetCampType; }
      set { _targetCampType = value; }
    }
    private int _targetCount = (int)1;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"targetCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int targetCount
    {
      get { return _targetCount; }
      set { _targetCount = value; }
    }
    private float _randomRate = (float)0;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"randomRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float randomRate
    {
      get { return _randomRate; }
      set { _randomRate = value; }
    }
    private bool _checkOnAIControl = default(bool);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"checkOnAIControl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkOnAIControl
    {
      get { return _checkOnAIControl; }
      set { _checkOnAIControl = value; }
    }
    private bool _checkInAction = default(bool);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"checkInAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkInAction
    {
      get { return _checkInAction; }
      set { _checkInAction = value; }
    }
    private bool _checkInAction_Reverse = default(bool);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"checkInAction_Reverse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkInAction_Reverse
    {
      get { return _checkInAction_Reverse; }
      set { _checkInAction_Reverse = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _checkActionList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(27, Name=@"checkActionList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> checkActionList
    {
      get { return _checkActionList; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _successLinkList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(9, Name=@"successLinkList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> successLinkList
    {
      get { return _successLinkList; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _failLinkList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(10, Name=@"failLinkList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> failLinkList
    {
      get { return _failLinkList; }
    }
  
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"CompareType")]
    public enum CompareType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MORE_THAN_TIME", Value=0)]
      MORE_THAN_TIME = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LESS_THAN_TIME", Value=1)]
      LESS_THAN_TIME = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"HittedTargetType")]
    public enum HittedTargetType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL_TARGET", Value=1)]
      ALL_TARGET = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHARACTER", Value=2)]
      CHARACTER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROJECTILE", Value=3)]
      PROJECTILE = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CampType")]
    public enum CampType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL_CAMP", Value=1)]
      ALL_CAMP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENT", Value=2)]
      CURRENT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENEMY", Value=3)]
      ENEMY = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SceneBlockHittest")]
    public enum SceneBlockHittest
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEVER", Value=0)]
      NEVER = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_COLLIDER", Value=1)]
      SCENE_COLLIDER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_WALL_COLLIDER", Value=2)]
      SCENE_WALL_COLLIDER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL_COLLIDER", Value=3)]
      ALL_COLLIDER = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AcceptDirection")]
    public enum AcceptDirection
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=0)]
      ALL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRONT", Value=1)]
      FRONT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BACK", Value=2)]
      BACK = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}