//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LDamageFormula.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LDamageFormula")]
  public partial class LDamageFormula : global::ProtoBuf.IExtensible
  {
    public LDamageFormula() {}
    
    private string _actionName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"actionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string actionName
    {
      get { return _actionName; }
      set { _actionName = value; }
    }
    private int _formulaType = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"formulaType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int formulaType
    {
      get { return _formulaType; }
      set { _formulaType = value; }
    }
    private int _paraA = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"paraA", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int paraA
    {
      get { return _paraA; }
      set { _paraA = value; }
    }
    private int _paraB = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"paraB", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int paraB
    {
      get { return _paraB; }
      set { _paraB = value; }
    }
    private float _constPara = (float)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"constPara", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float constPara
    {
      get { return _constPara; }
      set { _constPara = value; }
    }
    private float _factorA = (float)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"factorA", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float factorA
    {
      get { return _factorA; }
      set { _factorA = value; }
    }
    private float _factorB = (float)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"factorB", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float factorB
    {
      get { return _factorB; }
      set { _factorB = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}