//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LEvaluationData.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LEvaluationData")]
  public partial class LEvaluationData : global::ProtoBuf.IExtensible
  {
    public LEvaluationData() {}
    
    private readonly global::System.Collections.Generic.List<ActionData.LEvaluationData.LActionEvaluation> _actions = new global::System.Collections.Generic.List<ActionData.LEvaluationData.LActionEvaluation>();
    [global::ProtoBuf.ProtoMember(1, Name=@"actions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LEvaluationData.LActionEvaluation> actions
    {
      get { return _actions; }
    }
  
    private ActionData.LEvaluationData.LPerformanceRating _unitPerformanceRating = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"unitPerformanceRating", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LEvaluationData.LPerformanceRating unitPerformanceRating
    {
      get { return _unitPerformanceRating; }
      set { _unitPerformanceRating = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LActionEvaluation")]
  public partial class LActionEvaluation : global::ProtoBuf.IExtensible
  {
    public LActionEvaluation() {}
    
    private ActionData.LEvaluationData.LPerformanceRating _actionPerformanceRating = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"actionPerformanceRating", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LEvaluationData.LPerformanceRating actionPerformanceRating
    {
      get { return _actionPerformanceRating; }
      set { _actionPerformanceRating = value; }
    }
    private float _displacement;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"displacement", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float displacement
    {
      get { return _displacement; }
      set { _displacement = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode> _moves = new global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode>();
    [global::ProtoBuf.ProtoMember(3, Name=@"moves", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode> moves
    {
      get { return _moves; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode> _frontMoves = new global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode>();
    [global::ProtoBuf.ProtoMember(4, Name=@"frontMoves", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode> frontMoves
    {
      get { return _frontMoves; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode> _upMoves = new global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode>();
    [global::ProtoBuf.ProtoMember(5, Name=@"upMoves", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode> upMoves
    {
      get { return _upMoves; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode> _downMoves = new global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode>();
    [global::ProtoBuf.ProtoMember(6, Name=@"downMoves", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LEvaluationData.LMoveNode> downMoves
    {
      get { return _downMoves; }
    }
  
    private bool _isTeleport = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isTeleport", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isTeleport
    {
      get { return _isTeleport; }
      set { _isTeleport = value; }
    }
    private bool _isTracking = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"isTracking", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isTracking
    {
      get { return _isTracking; }
      set { _isTracking = value; }
    }
    private ActionData.LVector3 _rangeBoxCenter = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"rangeBoxCenter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 rangeBoxCenter
    {
      get { return _rangeBoxCenter; }
      set { _rangeBoxCenter = value; }
    }
    private ActionData.LVector3 _rangeBoxSize = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"rangeBoxSize", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 rangeBoxSize
    {
      get { return _rangeBoxSize; }
      set { _rangeBoxSize = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LPerformanceRating")]
  public partial class LPerformanceRating : global::ProtoBuf.IExtensible
  {
    public LPerformanceRating() {}
    
    private int _agileLevel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"agileLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int agileLevel
    {
      get { return _agileLevel; }
      set { _agileLevel = value; }
    }
    private int _breakLevel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"breakLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int breakLevel
    {
      get { return _breakLevel; }
      set { _breakLevel = value; }
    }
    private int _superArmorLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"superArmorLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int superArmorLevel
    {
      get { return _superArmorLevel; }
      set { _superArmorLevel = value; }
    }
    private int _skillRangeLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"skillRangeLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillRangeLevel
    {
      get { return _skillRangeLevel; }
      set { _skillRangeLevel = value; }
    }
    private int _skillDistanceLevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"skillDistanceLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillDistanceLevel
    {
      get { return _skillDistanceLevel; }
      set { _skillDistanceLevel = value; }
    }
    private int _pre_emptLevel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"pre_emptLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pre_emptLevel
    {
      get { return _pre_emptLevel; }
      set { _pre_emptLevel = value; }
    }
    private int _dogfightLevel;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"dogfightLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dogfightLevel
    {
      get { return _dogfightLevel; }
      set { _dogfightLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LMoveNode")]
  public partial class LMoveNode : global::ProtoBuf.IExtensible
  {
    public LMoveNode() {}
    
    private int _frame;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int frame
    {
      get { return _frame; }
      set { _frame = value; }
    }
    private float _movement;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"movement", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float movement
    {
      get { return _movement; }
      set { _movement = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}