//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LHitBehaviorData_Input.proto
// Note: requires additional types generated from: LHitEffectsData_Input.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LHitBehaviorData_Input")]
  public partial class LHitBehaviorData_Input : global::ProtoBuf.IExtensible
  {
    public LHitBehaviorData_Input() {}
    
    private int _id = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _hitTimes = (int)1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hitTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int hitTimes
    {
      get { return _hitTimes; }
      set { _hitTimes = value; }
    }
    private int _life = (int)0;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"life", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int life
    {
      get { return _life; }
      set { _life = value; }
    }
    private int _interval = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"interval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int interval
    {
      get { return _interval; }
      set { _interval = value; }
    }
    private float _hitDepthIn = (float)35;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hitDepthIn", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)35)]
    public float hitDepthIn
    {
      get { return _hitDepthIn; }
      set { _hitDepthIn = value; }
    }
    private float _hitDepthOut = (float)35;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"hitDepthOut", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)35)]
    public float hitDepthOut
    {
      get { return _hitDepthOut; }
      set { _hitDepthOut = value; }
    }
    private bool _hitLieDown = (bool)false;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hitLieDown", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool hitLieDown
    {
      get { return _hitLieDown; }
      set { _hitLieDown = value; }
    }
    private bool _floorRebound = (bool)false;
    [global::ProtoBuf.ProtoMember(81, IsRequired = false, Name=@"floorRebound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool floorRebound
    {
      get { return _floorRebound; }
      set { _floorRebound = value; }
    }
    private bool _wallRebound = (bool)false;
    [global::ProtoBuf.ProtoMember(82, IsRequired = false, Name=@"wallRebound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool wallRebound
    {
      get { return _wallRebound; }
      set { _wallRebound = value; }
    }
    private float _powerX = (float)4;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"powerX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)4)]
    public float powerX
    {
      get { return _powerX; }
      set { _powerX = value; }
    }
    private float _powerY = (float)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"powerY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float powerY
    {
      get { return _powerY; }
      set { _powerY = value; }
    }
    private float _powerZ = (float)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"powerZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float powerZ
    {
      get { return _powerZ; }
      set { _powerZ = value; }
    }
    private float _powerXAir = (float)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"powerXAir", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float powerXAir
    {
      get { return _powerXAir; }
      set { _powerXAir = value; }
    }
    private float _powerYAir = (float)1;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"powerYAir", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float powerYAir
    {
      get { return _powerYAir; }
      set { _powerYAir = value; }
    }
    private float _powerZAir = (float)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"powerZAir", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float powerZAir
    {
      get { return _powerZAir; }
      set { _powerZAir = value; }
    }
    private float _powerX_Random = (float)0;
    [global::ProtoBuf.ProtoMember(70, IsRequired = false, Name=@"powerX_Random", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float powerX_Random
    {
      get { return _powerX_Random; }
      set { _powerX_Random = value; }
    }
    private float _powerY_Random = (float)0;
    [global::ProtoBuf.ProtoMember(71, IsRequired = false, Name=@"powerY_Random", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float powerY_Random
    {
      get { return _powerY_Random; }
      set { _powerY_Random = value; }
    }
    private float _powerZ_Random = (float)0;
    [global::ProtoBuf.ProtoMember(72, IsRequired = false, Name=@"powerZ_Random", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float powerZ_Random
    {
      get { return _powerZ_Random; }
      set { _powerZ_Random = value; }
    }
    private float _powerX_Air_Random = (float)0;
    [global::ProtoBuf.ProtoMember(73, IsRequired = false, Name=@"powerX_Air_Random", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float powerX_Air_Random
    {
      get { return _powerX_Air_Random; }
      set { _powerX_Air_Random = value; }
    }
    private float _powerY_Air_Random = (float)0;
    [global::ProtoBuf.ProtoMember(74, IsRequired = false, Name=@"powerY_Air_Random", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float powerY_Air_Random
    {
      get { return _powerY_Air_Random; }
      set { _powerY_Air_Random = value; }
    }
    private float _powerZ_Air_Random = (float)0;
    [global::ProtoBuf.ProtoMember(75, IsRequired = false, Name=@"powerZ_Air_Random", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float powerZ_Air_Random
    {
      get { return _powerZ_Air_Random; }
      set { _powerZ_Air_Random = value; }
    }
    private bool _isCenterPower = (bool)false;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"isCenterPower", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool isCenterPower
    {
      get { return _isCenterPower; }
      set { _isCenterPower = value; }
    }
    private int _numbTime = (int)20;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"numbTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)20)]
    public int numbTime
    {
      get { return _numbTime; }
      set { _numbTime = value; }
    }
    private int _numbType = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"numbType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int numbType
    {
      get { return _numbType; }
      set { _numbType = value; }
    }
    private int _airNumbType = (int)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"airNumbType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int airNumbType
    {
      get { return _airNumbType; }
      set { _airNumbType = value; }
    }
    private bool _shake = (bool)true;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"shake", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool shake
    {
      get { return _shake; }
      set { _shake = value; }
    }
    private int _hitStopFrame = (int)3;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"hitStopFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)3)]
    public int hitStopFrame
    {
      get { return _hitStopFrame; }
      set { _hitStopFrame = value; }
    }
    private int _bearStopFrame = (int)3;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"bearStopFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)3)]
    public int bearStopFrame
    {
      get { return _bearStopFrame; }
      set { _bearStopFrame = value; }
    }
    private bool _holdBearStopFrame = (bool)false;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"holdBearStopFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool holdBearStopFrame
    {
      get { return _holdBearStopFrame; }
      set { _holdBearStopFrame = value; }
    }
    private bool _canGuard = (bool)false;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"canGuard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool canGuard
    {
      get { return _canGuard; }
      set { _canGuard = value; }
    }
    private int _knockDown = (int)0;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"knockDown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int knockDown
    {
      get { return _knockDown; }
      set { _knockDown = value; }
    }
    private int _airDown = (int)0;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"airDown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int airDown
    {
      get { return _airDown; }
      set { _airDown = value; }
    }
    private int _airKnockOut = (int)0;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"airKnockOut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int airKnockOut
    {
      get { return _airKnockOut; }
      set { _airKnockOut = value; }
    }
    private bool _enforceLanden = (bool)false;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"enforceLanden", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool enforceLanden
    {
      get { return _enforceLanden; }
      set { _enforceLanden = value; }
    }
    private bool _enforceFlyying = (bool)false;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"enforceFlyying", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool enforceFlyying
    {
      get { return _enforceFlyying; }
      set { _enforceFlyying = value; }
    }
    private bool _enforceLocate = (bool)false;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"enforceLocate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool enforceLocate
    {
      get { return _enforceLocate; }
      set { _enforceLocate = value; }
    }
    private ActionData.LVector3 _locator = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"locator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 locator
    {
      get { return _locator; }
      set { _locator = value; }
    }
    private int _locatorFrame = (int)0;
    [global::ProtoBuf.ProtoMember(83, IsRequired = false, Name=@"locatorFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int locatorFrame
    {
      get { return _locatorFrame; }
      set { _locatorFrame = value; }
    }
    private bool _enforceLocateIgnoreCollider = (bool)false;
    [global::ProtoBuf.ProtoMember(84, IsRequired = false, Name=@"enforceLocateIgnoreCollider", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool enforceLocateIgnoreCollider
    {
      get { return _enforceLocateIgnoreCollider; }
      set { _enforceLocateIgnoreCollider = value; }
    }
    private int _breakLevel = (int)1;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"breakLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int breakLevel
    {
      get { return _breakLevel; }
      set { _breakLevel = value; }
    }
    private bool _gameObjectLinkHitStopFrame = (bool)false;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"gameObjectLinkHitStopFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool gameObjectLinkHitStopFrame
    {
      get { return _gameObjectLinkHitStopFrame; }
      set { _gameObjectLinkHitStopFrame = value; }
    }
    private bool _high = default(bool);
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool high
    {
      get { return _high; }
      set { _high = value; }
    }
    private bool _middle = default(bool);
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"middle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool middle
    {
      get { return _middle; }
      set { _middle = value; }
    }
    private bool _low = default(bool);
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool low
    {
      get { return _low; }
      set { _low = value; }
    }
    private ActionData.LHitBehaviorData_Input.HitTargetSwitch _hitTargetSwitch = ActionData.LHitBehaviorData_Input.HitTargetSwitch.CHARACTER;
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"hitTargetSwitch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LHitBehaviorData_Input.HitTargetSwitch.CHARACTER)]
    public ActionData.LHitBehaviorData_Input.HitTargetSwitch hitTargetSwitch
    {
      get { return _hitTargetSwitch; }
      set { _hitTargetSwitch = value; }
    }
    private int _bounceLevel = default(int);
    [global::ProtoBuf.ProtoMember(61, IsRequired = false, Name=@"bounceLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bounceLevel
    {
      get { return _bounceLevel; }
      set { _bounceLevel = value; }
    }
    private int _destroyLevel = default(int);
    [global::ProtoBuf.ProtoMember(62, IsRequired = false, Name=@"destroyLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int destroyLevel
    {
      get { return _destroyLevel; }
      set { _destroyLevel = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"HitTargetSwitch")]
    public enum HitTargetSwitch
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHARACTER", Value=0)]
      CHARACTER = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROJECTILE", Value=1)]
      PROJECTILE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=2)]
      ALL = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}