//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LHitBoxGroupInput.proto
// Note: requires additional types generated from: LVector3.proto
// Note: requires additional types generated from: LHitBoxCellInput.proto
// Note: requires additional types generated from: LCheckSkillSwitchData.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LHitBoxGroupInput")]
  public partial class LHitBoxGroupInput : global::ProtoBuf.IExtensible
  {
    public LHitBoxGroupInput() {}
    
    private string _hitBoxName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hitBoxName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hitBoxName
    {
      get { return _hitBoxName; }
      set { _hitBoxName = value; }
    }
    private bool _isAttackbox = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isAttackbox", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAttackbox
    {
      get { return _isAttackbox; }
      set { _isAttackbox = value; }
    }
    private bool _isHurtbox = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isHurtbox", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isHurtbox
    {
      get { return _isHurtbox; }
      set { _isHurtbox = value; }
    }
    private bool _isColliderbox = default(bool);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"isColliderbox", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isColliderbox
    {
      get { return _isColliderbox; }
      set { _isColliderbox = value; }
    }
    private ActionData.LHitBoxGroupInput.CampTestType _campTestType = ActionData.LHitBoxGroupInput.CampTestType.ENEMY;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"campTestType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LHitBoxGroupInput.CampTestType.ENEMY)]
    public ActionData.LHitBoxGroupInput.CampTestType campTestType
    {
      get { return _campTestType; }
      set { _campTestType = value; }
    }
    private float _minActionTime = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"minActionTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float minActionTime
    {
      get { return _minActionTime; }
      set { _minActionTime = value; }
    }
    private float _maxActionTime = (float)1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxActionTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float maxActionTime
    {
      get { return _maxActionTime; }
      set { _maxActionTime = value; }
    }
    private int _severId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"severId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int severId
    {
      get { return _severId; }
      set { _severId = value; }
    }
    private int _hitId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hitId
    {
      get { return _hitId; }
      set { _hitId = value; }
    }
    private bool _passSynHit = (bool)false;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"passSynHit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool passSynHit
    {
      get { return _passSynHit; }
      set { _passSynHit = value; }
    }
    private ActionData.LVector3 _localPosition = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"localPosition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 localPosition
    {
      get { return _localPosition; }
      set { _localPosition = value; }
    }
    private ActionData.LVector3 _localScale = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"localScale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 localScale
    {
      get { return _localScale; }
      set { _localScale = value; }
    }
    private ActionData.LVector3 _localRotation = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"localRotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 localRotation
    {
      get { return _localRotation; }
      set { _localRotation = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LHitBoxCellInput> _hitBoxCellInputList = new global::System.Collections.Generic.List<ActionData.LHitBoxCellInput>();
    [global::ProtoBuf.ProtoMember(9, Name=@"hitBoxCellInputList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LHitBoxCellInput> hitBoxCellInputList
    {
      get { return _hitBoxCellInputList; }
    }
  
    private int _endureLevel = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"endureLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int endureLevel
    {
      get { return _endureLevel; }
      set { _endureLevel = value; }
    }
    private float _forceResistance = default(float);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"forceResistance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float forceResistance
    {
      get { return _forceResistance; }
      set { _forceResistance = value; }
    }
    private bool _high = default(bool);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool high
    {
      get { return _high; }
      set { _high = value; }
    }
    private bool _middle = default(bool);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"middle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool middle
    {
      get { return _middle; }
      set { _middle = value; }
    }
    private bool _low = default(bool);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool low
    {
      get { return _low; }
      set { _low = value; }
    }
    private bool _isAllRange = default(bool);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"isAllRange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAllRange
    {
      get { return _isAllRange; }
      set { _isAllRange = value; }
    }
    private int _bounceLevel = default(int);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"bounceLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bounceLevel
    {
      get { return _bounceLevel; }
      set { _bounceLevel = value; }
    }
    private int _destroyLevel = default(int);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"destroyLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int destroyLevel
    {
      get { return _destroyLevel; }
      set { _destroyLevel = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LCheckSkillSwitchData> _checkSkillSwitchData = new global::System.Collections.Generic.List<ActionData.LCheckSkillSwitchData>();
    [global::ProtoBuf.ProtoMember(101, Name=@"checkSkillSwitchData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCheckSkillSwitchData> checkSkillSwitchData
    {
      get { return _checkSkillSwitchData; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CampTestType")]
    public enum CampTestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENEMY", Value=0)]
      ENEMY = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENT", Value=1)]
      CURRENT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOTH", Value=2)]
      BOTH = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELF", Value=3)]
      SELF = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}