//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LInvincible.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LInvincible")]
  public partial class LInvincible : global::ProtoBuf.IExtensible
  {
    public LInvincible() {}
    
    private float _time = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }
    private float _R = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"R", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float R
    {
      get { return _R; }
      set { _R = value; }
    }
    private float _G = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"G", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float G
    {
      get { return _G; }
      set { _G = value; }
    }
    private float _B = (float)0.5;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"B", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0.5)]
    public float B
    {
      get { return _B; }
      set { _B = value; }
    }
    private bool _remove = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"remove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool remove
    {
      get { return _remove; }
      set { _remove = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}