//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LModifyProjectile.proto
// Note: requires additional types generated from: LTimeEventProType.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LModifyProjectile")]
  public partial class LModifyProjectile : global::ProtoBuf.IExtensible
  {
    public LModifyProjectile() {}
    
    private ActionData.LModifyProjectile.TypeName _typeName = ActionData.LModifyProjectile.TypeName.DEFAULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"typeName", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LModifyProjectile.TypeName.DEFAULT)]
    public ActionData.LModifyProjectile.TypeName typeName
    {
      get { return _typeName; }
      set { _typeName = value; }
    }
    private bool _keepSpeed = default(bool);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"keepSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool keepSpeed
    {
      get { return _keepSpeed; }
      set { _keepSpeed = value; }
    }
    private bool _keepAngle = default(bool);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"keepAngle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool keepAngle
    {
      get { return _keepAngle; }
      set { _keepAngle = value; }
    }
    private int _mergeFrame = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"mergeFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mergeFrame
    {
      get { return _mergeFrame; }
      set { _mergeFrame = value; }
    }
    private ActionData.LVector3 _position2 = null;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"position2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 position2
    {
      get { return _position2; }
      set { _position2 = value; }
    }
    private bool _autoHalfHeight = (bool)true;
    [global::ProtoBuf.ProtoMember(63, IsRequired = false, Name=@"autoHalfHeight", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool autoHalfHeight
    {
      get { return _autoHalfHeight; }
      set { _autoHalfHeight = value; }
    }
    private ActionData.LVector3 _angle = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private bool _autoChangeAngle = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"autoChangeAngle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool autoChangeAngle
    {
      get { return _autoChangeAngle; }
      set { _autoChangeAngle = value; }
    }
    private bool _placeToFoothol = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"placeToFoothol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool placeToFoothol
    {
      get { return _placeToFoothol; }
      set { _placeToFoothol = value; }
    }
    private ActionData.LVector3 _randomAngleRange = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"randomAngleRange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 randomAngleRange
    {
      get { return _randomAngleRange; }
      set { _randomAngleRange = value; }
    }
    private float _speed = (float)5;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)5)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private float _acceleration = (float)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"acceleration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float acceleration
    {
      get { return _acceleration; }
      set { _acceleration = value; }
    }
    private float _randomSpeed = (float)0;
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"randomSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float randomSpeed
    {
      get { return _randomSpeed; }
      set { _randomSpeed = value; }
    }
    private bool _randomSpeedDirection = default(bool);
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"randomSpeedDirection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool randomSpeedDirection
    {
      get { return _randomSpeedDirection; }
      set { _randomSpeedDirection = value; }
    }
    private ActionData.LVector3 _fieldForce = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fieldForce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 fieldForce
    {
      get { return _fieldForce; }
      set { _fieldForce = value; }
    }
    private bool _lockDirection = default(bool);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"lockDirection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool lockDirection
    {
      get { return _lockDirection; }
      set { _lockDirection = value; }
    }
    private ActionData.LVector3 _sizeBySpeed = null;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"sizeBySpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 sizeBySpeed
    {
      get { return _sizeBySpeed; }
      set { _sizeBySpeed = value; }
    }
    private float _trackingRate = (float)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"trackingRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float trackingRate
    {
      get { return _trackingRate; }
      set { _trackingRate = value; }
    }
    private ActionData.LModifyProjectile.Camp _camp = ActionData.LModifyProjectile.Camp.CURRENT_CAMP;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LModifyProjectile.Camp.CURRENT_CAMP)]
    public ActionData.LModifyProjectile.Camp camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private bool _bindBone = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"bindBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bindBone
    {
      get { return _bindBone; }
      set { _bindBone = value; }
    }
    private string _bindName = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"bindName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bindName
    {
      get { return _bindName; }
      set { _bindName = value; }
    }
    private ActionData.LVector3 _boneOffset = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"boneOffset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 boneOffset
    {
      get { return _boneOffset; }
      set { _boneOffset = value; }
    }
    private ActionData.LModifyProjectile.SurroundType _surroundType = ActionData.LModifyProjectile.SurroundType.SURROUND_LOCATE;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"surroundType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LModifyProjectile.SurroundType.SURROUND_LOCATE)]
    public ActionData.LModifyProjectile.SurroundType surroundType
    {
      get { return _surroundType; }
      set { _surroundType = value; }
    }
    private ActionData.LVector3 _surroundOffset = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"surroundOffset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 surroundOffset
    {
      get { return _surroundOffset; }
      set { _surroundOffset = value; }
    }
    private ActionData.LVector3 _surroundOffsetRandom = null;
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"surroundOffsetRandom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 surroundOffsetRandom
    {
      get { return _surroundOffsetRandom; }
      set { _surroundOffsetRandom = value; }
    }
    private float _surroundRadius = (float)1;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"surroundRadius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float surroundRadius
    {
      get { return _surroundRadius; }
      set { _surroundRadius = value; }
    }
    private float _surroundRadiusChangeSpeed = (float)0;
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"surroundRadiusChangeSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float surroundRadiusChangeSpeed
    {
      get { return _surroundRadiusChangeSpeed; }
      set { _surroundRadiusChangeSpeed = value; }
    }
    private float _surroundRadiusRandom = (float)0;
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"surroundRadiusRandom", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float surroundRadiusRandom
    {
      get { return _surroundRadiusRandom; }
      set { _surroundRadiusRandom = value; }
    }
    private ActionData.LVector3 _surroundScale = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"surroundScale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 surroundScale
    {
      get { return _surroundScale; }
      set { _surroundScale = value; }
    }
    private ActionData.LVector3 _surroundRotation = null;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"surroundRotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 surroundRotation
    {
      get { return _surroundRotation; }
      set { _surroundRotation = value; }
    }
    private bool _dontDestroyWithTarget = default(bool);
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"dontDestroyWithTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool dontDestroyWithTarget
    {
      get { return _dontDestroyWithTarget; }
      set { _dontDestroyWithTarget = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"TypeName")]
    public enum TypeName
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEFAULT", Value=0)]
      DEFAULT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOLLOW", Value=1)]
      FOLLOW = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SURROUND", Value=2)]
      SURROUND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PARABOLA", Value=3)]
      PARABOLA = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Camp")]
    public enum Camp
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENT_CAMP", Value=0)]
      CURRENT_CAMP = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVERSE_CAMP", Value=1)]
      INVERSE_CAMP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEUTRAL_CAMP", Value=2)]
      NEUTRAL_CAMP = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SurroundType")]
    public enum SurroundType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SURROUND_LOCATE", Value=0)]
      SURROUND_LOCATE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SURROUND_RING", Value=1)]
      SURROUND_RING = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SURROUND_SPHERE", Value=2)]
      SURROUND_SPHERE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SURROUND_RANDOM", Value=3)]
      SURROUND_RANDOM = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}