//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LPlaySelfAnimation.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LPlaySelfAnimation")]
  public partial class LPlaySelfAnimation : global::ProtoBuf.IExtensible
  {
    public LPlaySelfAnimation() {}
    
    private string _clipName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"clipName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clipName
    {
      get { return _clipName; }
      set { _clipName = value; }
    }
    private float _crossFadeTime = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"crossFadeTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float crossFadeTime
    {
      get { return _crossFadeTime; }
      set { _crossFadeTime = value; }
    }
    private float _playSpeed = (float)1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float playSpeed
    {
      get { return _playSpeed; }
      set { _playSpeed = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}