//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LProjectileModelData.proto
// Note: requires additional types generated from: LVector3.proto
// Note: requires additional types generated from: LAddProjectile.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LProjectileModelData")]
  public partial class LProjectileModelData : global::ProtoBuf.IExtensible
  {
    public LProjectileModelData() {}
    
    private string _effectId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"effectId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string effectId
    {
      get { return _effectId; }
      set { _effectId = value; }
    }
    private string _prototypeID;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"prototypeID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string prototypeID
    {
      get { return _prototypeID; }
      set { _prototypeID = value; }
    }
    private string _projectileId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"projectileId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string projectileId
    {
      get { return _projectileId; }
      set { _projectileId = value; }
    }
    private float _lifeTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lifeTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float lifeTime
    {
      get { return _lifeTime; }
      set { _lifeTime = value; }
    }
    private int _hitTimes;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hitTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hitTimes
    {
      get { return _hitTimes; }
      set { _hitTimes = value; }
    }
    private bool _isBlock = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isBlock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBlock
    {
      get { return _isBlock; }
      set { _isBlock = value; }
    }
    private string _layer = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"layer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string layer
    {
      get { return _layer; }
      set { _layer = value; }
    }
    private ActionData.LVector3 _colliderCenter = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"colliderCenter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 colliderCenter
    {
      get { return _colliderCenter; }
      set { _colliderCenter = value; }
    }
    private ActionData.LVector3 _colliderSize = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"colliderSize", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 colliderSize
    {
      get { return _colliderSize; }
      set { _colliderSize = value; }
    }
    private bool _synAction = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"synAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool synAction
    {
      get { return _synAction; }
      set { _synAction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}