//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LRandomToAction.proto
// Note: requires additional types generated from: LTimeEventProType.proto
// Note: requires additional types generated from: LToAction.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LRandomToAction")]
  public partial class LRandomToAction : global::ProtoBuf.IExtensible
  {
    public LRandomToAction() {}
    
    private readonly global::System.Collections.Generic.List<ActionData.LRandomToAction.RandomAction> _randomAction = new global::System.Collections.Generic.List<ActionData.LRandomToAction.RandomAction>();
    [global::ProtoBuf.ProtoMember(1, Name=@"randomAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LRandomToAction.RandomAction> randomAction
    {
      get { return _randomAction; }
    }
  
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RandomAction")]
  public partial class RandomAction : global::ProtoBuf.IExtensible
  {
    public RandomAction() {}
    
    private string _actionName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"actionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string actionName
    {
      get { return _actionName; }
      set { _actionName = value; }
    }
    private int _weight = (int)100;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"weight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)100)]
    public int weight
    {
      get { return _weight; }
      set { _weight = value; }
    }
    private bool _reset = (bool)true;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool reset
    {
      get { return _reset; }
      set { _reset = value; }
    }
    private int _startFrame = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"startFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startFrame
    {
      get { return _startFrame; }
      set { _startFrame = value; }
    }
    private bool _checkSkill = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"checkSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkSkill
    {
      get { return _checkSkill; }
      set { _checkSkill = value; }
    }
    private bool _checkCancelPriority = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"checkCancelPriority", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkCancelPriority
    {
      get { return _checkCancelPriority; }
      set { _checkCancelPriority = value; }
    }
    private float _fadeTime = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fadeTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float fadeTime
    {
      get { return _fadeTime; }
      set { _fadeTime = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LToAction.SwitchData> _switchDo = new global::System.Collections.Generic.List<ActionData.LToAction.SwitchData>();
    [global::ProtoBuf.ProtoMember(7, Name=@"switchDo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LToAction.SwitchData> switchDo
    {
      get { return _switchDo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}