//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LSendEvent.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LSendEvent")]
  public partial class LSendEvent : global::ProtoBuf.IExtensible
  {
    public LSendEvent() {}
    
    private string _event;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"event", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string @event
    {
      get { return _event; }
      set { _event = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _parameter = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"parameter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> parameter
    {
      get { return _parameter; }
    }
  
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(100, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}