//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LShakeCamera.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LShakeCamera")]
  public partial class LShakeCamera : global::ProtoBuf.IExtensible
  {
    public LShakeCamera() {}
    
    private float _shakeRange = (float)0.1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"shakeRange", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0.1)]
    public float shakeRange
    {
      get { return _shakeRange; }
      set { _shakeRange = value; }
    }
    private float _shakeInterval = (float)0.015;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shakeInterval", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0.015)]
    public float shakeInterval
    {
      get { return _shakeInterval; }
      set { _shakeInterval = value; }
    }
    private float _shakeRangeAccSpeed = (float)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"shakeRangeAccSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)-1)]
    public float shakeRangeAccSpeed
    {
      get { return _shakeRangeAccSpeed; }
      set { _shakeRangeAccSpeed = value; }
    }
    private float _firstMinAngle = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"firstMinAngle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float firstMinAngle
    {
      get { return _firstMinAngle; }
      set { _firstMinAngle = value; }
    }
    private float _firstMaxAngle = (float)360;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"firstMaxAngle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)360)]
    public float firstMaxAngle
    {
      get { return _firstMaxAngle; }
      set { _firstMaxAngle = value; }
    }
    private float _scale = (float)1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private bool _isDoubleSidedAngle = (bool)true;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isDoubleSidedAngle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool isDoubleSidedAngle
    {
      get { return _isDoubleSidedAngle; }
      set { _isDoubleSidedAngle = value; }
    }
    private float _minAngle = (float)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"minAngle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float minAngle
    {
      get { return _minAngle; }
      set { _minAngle = value; }
    }
    private float _maxAngle = (float)360;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"maxAngle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)360)]
    public float maxAngle
    {
      get { return _maxAngle; }
      set { _maxAngle = value; }
    }
    private bool _shakeUI = (bool)false;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"shakeUI", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool shakeUI
    {
      get { return _shakeUI; }
      set { _shakeUI = value; }
    }
    private float _cScaleRange = (float)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"cScaleRange", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float cScaleRange
    {
      get { return _cScaleRange; }
      set { _cScaleRange = value; }
    }
    private float _scaleInterval = (float)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"scaleInterval", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float scaleInterval
    {
      get { return _scaleInterval; }
      set { _scaleInterval = value; }
    }
    private float _scaleAccSpeed = (float)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"scaleAccSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float scaleAccSpeed
    {
      get { return _scaleAccSpeed; }
      set { _scaleAccSpeed = value; }
    }
    private bool _isFirstMaxRange = (bool)true;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"isFirstMaxRange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool isFirstMaxRange
    {
      get { return _isFirstMaxRange; }
      set { _isFirstMaxRange = value; }
    }
    private ActionData.LTimeEventProType _eventType = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private float _shakeAccInterval = (float)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"shakeAccInterval", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float shakeAccInterval
    {
      get { return _shakeAccInterval; }
      set { _shakeAccInterval = value; }
    }
    private float _shakeOffsetMax = (float)1.1;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"shakeOffsetMax", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1.1)]
    public float shakeOffsetMax
    {
      get { return _shakeOffsetMax; }
      set { _shakeOffsetMax = value; }
    }
    private float _shakeOffsetMin = (float)0.9;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"shakeOffsetMin", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0.9)]
    public float shakeOffsetMin
    {
      get { return _shakeOffsetMin; }
      set { _shakeOffsetMin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}