//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LTargetOperation.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LTargetOperation")]
  public partial class LTargetOperation : global::ProtoBuf.IExtensible
  {
    public LTargetOperation() {}
    
    private ActionData.LTargetOperation.TargetType _targetType = ActionData.LTargetOperation.TargetType.POSITIVE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ActionData.LTargetOperation.TargetType.POSITIVE)]
    public ActionData.LTargetOperation.TargetType targetType
    {
      get { return _targetType; }
      set { _targetType = value; }
    }
    private int _number = (int)1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _linkID = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(10, Name=@"linkID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> linkID
    {
      get { return _linkID; }
    }
  
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(99, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"TargetType")]
    public enum TargetType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"POSITIVE", Value=0)]
      POSITIVE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANDOM", Value=1)]
      RANDOM = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}