//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LToAction.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LToAction")]
  public partial class LToAction : global::ProtoBuf.IExtensible
  {
    public LToAction() {}
    
    private string _actionName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"actionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string actionName
    {
      get { return _actionName; }
      set { _actionName = value; }
    }
    private bool _reset = (bool)true;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool reset
    {
      get { return _reset; }
      set { _reset = value; }
    }
    private int _startFrame = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"startFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startFrame
    {
      get { return _startFrame; }
      set { _startFrame = value; }
    }
    private bool _checkSkill = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"checkSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkSkill
    {
      get { return _checkSkill; }
      set { _checkSkill = value; }
    }
    private bool _checkCancelPriority = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"checkCancelPriority", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool checkCancelPriority
    {
      get { return _checkCancelPriority; }
      set { _checkCancelPriority = value; }
    }
    private float _fadeTime = (float)-1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fadeTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)-1)]
    public float fadeTime
    {
      get { return _fadeTime; }
      set { _fadeTime = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LToAction.SwitchData> _switchDo = new global::System.Collections.Generic.List<ActionData.LToAction.SwitchData>();
    [global::ProtoBuf.ProtoMember(7, Name=@"switchDo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LToAction.SwitchData> switchDo
    {
      get { return _switchDo; }
    }
  
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwitchData")]
  public partial class SwitchData : global::ProtoBuf.IExtensible
  {
    public SwitchData() {}
    
    private string _targetActionName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetActionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string targetActionName
    {
      get { return _targetActionName; }
      set { _targetActionName = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _successLinkList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"successLinkList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> successLinkList
    {
      get { return _successLinkList; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _failLinkList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"failLinkList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> failLinkList
    {
      get { return _failLinkList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}