//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LVectorAssociateDuration.proto
// Note: requires additional types generated from: LVector3.proto
// Note: requires additional types generated from: LTimeEventProType.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LVectorAssociateDuration")]
  public partial class LVectorAssociateDuration : global::ProtoBuf.IExtensible
  {
    public LVectorAssociateDuration() {}
    
    private ActionData.LVector3 _angleOffset = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angleOffset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 angleOffset
    {
      get { return _angleOffset; }
      set { _angleOffset = value; }
    }
    private float _rate = (float)1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float rate
    {
      get { return _rate; }
      set { _rate = value; }
    }
    private bool _bindAction = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bindAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool bindAction
    {
      get { return _bindAction; }
      set { _bindAction = value; }
    }
    private ActionData.LTimeEventProType _eventType;
    [global::ProtoBuf.ProtoMember(101, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LTimeEventProType eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}