//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MoveTestData.proto
// Note: requires additional types generated from: LVector3.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveTestData")]
  public partial class MoveTestData : global::ProtoBuf.IExtensible
  {
    public MoveTestData() {}
    
    private readonly global::System.Collections.Generic.List<ActionData.MoveTestData.ActionMoveData> _actionMoveDataList = new global::System.Collections.Generic.List<ActionData.MoveTestData.ActionMoveData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"actionMoveDataList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.MoveTestData.ActionMoveData> actionMoveDataList
    {
      get { return _actionMoveDataList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActionMoveData")]
  public partial class ActionMoveData : global::ProtoBuf.IExtensible
  {
    public ActionMoveData() {}
    
    private string _actionLabel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"actionLabel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string actionLabel
    {
      get { return _actionLabel; }
      set { _actionLabel = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.MoveTestData.MoveData> _moveDatas = new global::System.Collections.Generic.List<ActionData.MoveTestData.MoveData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"moveDatas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.MoveTestData.MoveData> moveDatas
    {
      get { return _moveDatas; }
    }
  
    private bool _isPassCheck = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isPassCheck", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isPassCheck
    {
      get { return _isPassCheck; }
      set { _isPassCheck = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveData")]
  public partial class MoveData : global::ProtoBuf.IExtensible
  {
    public MoveData() {}
    
    private int _frameIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int frameIndex
    {
      get { return _frameIndex; }
      set { _frameIndex = value; }
    }
    private ActionData.LVector3 _absoluteSpeed = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"absoluteSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 absoluteSpeed
    {
      get { return _absoluteSpeed; }
      set { _absoluteSpeed = value; }
    }
    private ActionData.LVector3 _rateSpeed = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rateSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 rateSpeed
    {
      get { return _rateSpeed; }
      set { _rateSpeed = value; }
    }
    private ActionData.LVector3 _absoluteSpeed_Key = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"absoluteSpeed_Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 absoluteSpeed_Key
    {
      get { return _absoluteSpeed_Key; }
      set { _absoluteSpeed_Key = value; }
    }
    private ActionData.LVector3 _rateSpeed_Key = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rateSpeed_Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActionData.LVector3 rateSpeed_Key
    {
      get { return _rateSpeed_Key; }
      set { _rateSpeed_Key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}