//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: OneActionData.proto
// Note: requires additional types generated from: LPlaySelfAnimation.proto
// Note: requires additional types generated from: LToAction.proto
// Note: requires additional types generated from: LAddCancelPoint.proto
// Note: requires additional types generated from: LChangeDirection.proto
// Note: requires additional types generated from: LChangeDirectionByKeyState.proto
// Note: requires additional types generated from: LAutoMove.proto
// Note: requires additional types generated from: LAutoMoveDuration.proto
// Note: requires additional types generated from: LChangeAutoMoveSpeed.proto
// Note: requires additional types generated from: LStopAutoMove.proto
// Note: requires additional types generated from: LMoveByKeyState.proto
// Note: requires additional types generated from: LMoveByKeyStateDuration.proto
// Note: requires additional types generated from: LStopMoveByKey.proto
// Note: requires additional types generated from: LJump.proto
// Note: requires additional types generated from: LCrossPlatform.proto
// Note: requires additional types generated from: LAddEffect.proto
// Note: requires additional types generated from: LAddProjectile.proto
// Note: requires additional types generated from: LAddCustomProjectile.proto
// Note: requires additional types generated from: LModifyProjectile.proto
// Note: requires additional types generated from: LModifyCamera.proto
// Note: requires additional types generated from: LCameraMove.proto
// Note: requires additional types generated from: LCameraBackToMyPlayer.proto
// Note: requires additional types generated from: LCameraBackToCharacter.proto
// Note: requires additional types generated from: LMoveToNearTarget.proto
// Note: requires additional types generated from: LFaceToNearTarget.proto
// Note: requires additional types generated from: LChangeGravity.proto
// Note: requires additional types generated from: LAddSoundEvent.proto
// Note: requires additional types generated from: LAddRandomSoundEvent.proto
// Note: requires additional types generated from: LAddShock.proto
// Note: requires additional types generated from: LActionBaseInfo.proto
// Note: requires additional types generated from: LAddComboRespond.proto
// Note: requires additional types generated from: LTeleport.proto
// Note: requires additional types generated from: LSummonCharacter.proto
// Note: requires additional types generated from: LDestroyMe.proto
// Note: requires additional types generated from: LAddBuff.proto
// Note: requires additional types generated from: LConditionsLinker.proto
// Note: requires additional types generated from: LConditionsLinkerDuration.proto
// Note: requires additional types generated from: LChangeCamp.proto
// Note: requires additional types generated from: LAddSkillCollider.proto
// Note: requires additional types generated from: LTransfiguration.proto
// Note: requires additional types generated from: LChangeBehaviorType.proto
// Note: requires additional types generated from: LJumpToTarget.proto
// Note: requires additional types generated from: LMarkTarget.proto
// Note: requires additional types generated from: LResetActionState.proto
// Note: requires additional types generated from: LInvincible.proto
// Note: requires additional types generated from: LClearComboCatch.proto
// Note: requires additional types generated from: LAddForceField.proto
// Note: requires additional types generated from: LChangeAnimationSpeed.proto
// Note: requires additional types generated from: LHitBoxGroupInput.proto
// Note: requires additional types generated from: LEventData.proto
// Note: requires additional types generated from: LChangeBodyDirection.proto
// Note: requires additional types generated from: LShakeCamera.proto
// Note: requires additional types generated from: LAddSceneEffect.proto
// Note: requires additional types generated from: LResetCamera.proto
// Note: requires additional types generated from: LSwitchModel.proto
// Note: requires additional types generated from: LRandomToAction.proto
// Note: requires additional types generated from: LChangeStance.proto
// Note: requires additional types generated from: LCheckKeyState.proto
// Note: requires additional types generated from: LFindTarget.proto
// Note: requires additional types generated from: LTargetOperation.proto
// Note: requires additional types generated from: LModifyCharacterView.proto
// Note: requires additional types generated from: LDestroyTarget.proto
// Note: requires additional types generated from: LSetValue.proto
// Note: requires additional types generated from: LGenericSwitcher.proto
// Note: requires additional types generated from: LTimeStop.proto
// Note: requires additional types generated from: LAddBlur.proto
// Note: requires additional types generated from: LAddPhantom.proto
// Note: requires additional types generated from: LRemovePhantom.proto
// Note: requires additional types generated from: LVectorAssociateDuration.proto
// Note: requires additional types generated from: LAddColorSeparation.proto
// Note: requires additional types generated from: LAddGodRay.proto
// Note: requires additional types generated from: LAddRadialblur.proto
// Note: requires additional types generated from: LAddJoystickRespond.proto
// Note: requires additional types generated from: LMoveByJoystickDuration.proto
// Note: requires additional types generated from: LChangeTimeScale.proto
// Note: requires additional types generated from: LModifyUIVisible.proto
// Note: requires additional types generated from: LSendEvent.proto
// Note: requires additional types generated from: LChangeActionSpeed.proto
namespace ActionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OneActionData")]
  public partial class OneActionData : global::ProtoBuf.IExtensible
  {
    public OneActionData() {}
    
    private string _actionName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"actionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string actionName
    {
      get { return _actionName; }
      set { _actionName = value; }
    }
    private float _MoviceTimeLength = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"MoviceTimeLength", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float MoviceTimeLength
    {
      get { return _MoviceTimeLength; }
      set { _MoviceTimeLength = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LHitBoxGroupInput> _hitBoxGroupInputList = new global::System.Collections.Generic.List<ActionData.LHitBoxGroupInput>();
    [global::ProtoBuf.ProtoMember(3, Name=@"hitBoxGroupInputList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LHitBoxGroupInput> hitBoxGroupInputList
    {
      get { return _hitBoxGroupInputList; }
    }
  
    private bool _noe = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"noe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool noe
    {
      get { return _noe; }
      set { _noe = value; }
    }
    private bool _oneActionEnalbe = (bool)true;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"oneActionEnalbe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool oneActionEnalbe
    {
      get { return _oneActionEnalbe; }
      set { _oneActionEnalbe = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LPlaySelfAnimation> _PlaySelfAnimation = new global::System.Collections.Generic.List<ActionData.LPlaySelfAnimation>();
    [global::ProtoBuf.ProtoMember(6, Name=@"PlaySelfAnimation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LPlaySelfAnimation> PlaySelfAnimation
    {
      get { return _PlaySelfAnimation; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LToAction> _ToAction = new global::System.Collections.Generic.List<ActionData.LToAction>();
    [global::ProtoBuf.ProtoMember(7, Name=@"ToAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LToAction> ToAction
    {
      get { return _ToAction; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddCancelPoint> _AddCancelPoint = new global::System.Collections.Generic.List<ActionData.LAddCancelPoint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"AddCancelPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddCancelPoint> AddCancelPoint
    {
      get { return _AddCancelPoint; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeDirection> _ChangeDirection = new global::System.Collections.Generic.List<ActionData.LChangeDirection>();
    [global::ProtoBuf.ProtoMember(9, Name=@"ChangeDirection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeDirection> ChangeDirection
    {
      get { return _ChangeDirection; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeDirectionByKeyState> _ChangeDirectionByKeyState = new global::System.Collections.Generic.List<ActionData.LChangeDirectionByKeyState>();
    [global::ProtoBuf.ProtoMember(10, Name=@"ChangeDirectionByKeyState", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeDirectionByKeyState> ChangeDirectionByKeyState
    {
      get { return _ChangeDirectionByKeyState; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAutoMove> _AutoMove = new global::System.Collections.Generic.List<ActionData.LAutoMove>();
    [global::ProtoBuf.ProtoMember(11, Name=@"AutoMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAutoMove> AutoMove
    {
      get { return _AutoMove; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAutoMoveDuration> _AutoMoveDuration = new global::System.Collections.Generic.List<ActionData.LAutoMoveDuration>();
    [global::ProtoBuf.ProtoMember(12, Name=@"AutoMoveDuration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAutoMoveDuration> AutoMoveDuration
    {
      get { return _AutoMoveDuration; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeAutoMoveSpeed> _ChangeAutoMoveSpeed = new global::System.Collections.Generic.List<ActionData.LChangeAutoMoveSpeed>();
    [global::ProtoBuf.ProtoMember(13, Name=@"ChangeAutoMoveSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeAutoMoveSpeed> ChangeAutoMoveSpeed
    {
      get { return _ChangeAutoMoveSpeed; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LStopAutoMove> _StopAutoMove = new global::System.Collections.Generic.List<ActionData.LStopAutoMove>();
    [global::ProtoBuf.ProtoMember(14, Name=@"StopAutoMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LStopAutoMove> StopAutoMove
    {
      get { return _StopAutoMove; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LMoveByKeyState> _MoveByKeyState = new global::System.Collections.Generic.List<ActionData.LMoveByKeyState>();
    [global::ProtoBuf.ProtoMember(15, Name=@"MoveByKeyState", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LMoveByKeyState> MoveByKeyState
    {
      get { return _MoveByKeyState; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LMoveByKeyStateDuration> _MoveByKeyStateDuration = new global::System.Collections.Generic.List<ActionData.LMoveByKeyStateDuration>();
    [global::ProtoBuf.ProtoMember(16, Name=@"MoveByKeyStateDuration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LMoveByKeyStateDuration> MoveByKeyStateDuration
    {
      get { return _MoveByKeyStateDuration; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LStopMoveByKey> _StopMoveByKey = new global::System.Collections.Generic.List<ActionData.LStopMoveByKey>();
    [global::ProtoBuf.ProtoMember(17, Name=@"StopMoveByKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LStopMoveByKey> StopMoveByKey
    {
      get { return _StopMoveByKey; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LJump> _Jump = new global::System.Collections.Generic.List<ActionData.LJump>();
    [global::ProtoBuf.ProtoMember(18, Name=@"Jump", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LJump> Jump
    {
      get { return _Jump; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LCrossPlatform> _CrossPlatform = new global::System.Collections.Generic.List<ActionData.LCrossPlatform>();
    [global::ProtoBuf.ProtoMember(19, Name=@"CrossPlatform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCrossPlatform> CrossPlatform
    {
      get { return _CrossPlatform; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddEffect> _AddEffect = new global::System.Collections.Generic.List<ActionData.LAddEffect>();
    [global::ProtoBuf.ProtoMember(20, Name=@"AddEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddEffect> AddEffect
    {
      get { return _AddEffect; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddProjectile> _AddProjectile = new global::System.Collections.Generic.List<ActionData.LAddProjectile>();
    [global::ProtoBuf.ProtoMember(21, Name=@"AddProjectile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddProjectile> AddProjectile
    {
      get { return _AddProjectile; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddCustomProjectile> _AddCustomProjectile = new global::System.Collections.Generic.List<ActionData.LAddCustomProjectile>();
    [global::ProtoBuf.ProtoMember(22, Name=@"AddCustomProjectile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddCustomProjectile> AddCustomProjectile
    {
      get { return _AddCustomProjectile; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LModifyProjectile> _ModifyProjectile = new global::System.Collections.Generic.List<ActionData.LModifyProjectile>();
    [global::ProtoBuf.ProtoMember(23, Name=@"ModifyProjectile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LModifyProjectile> ModifyProjectile
    {
      get { return _ModifyProjectile; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LCameraMove> _CameraMove = new global::System.Collections.Generic.List<ActionData.LCameraMove>();
    [global::ProtoBuf.ProtoMember(25, Name=@"CameraMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCameraMove> CameraMove
    {
      get { return _CameraMove; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LCameraBackToMyPlayer> _CameraBackToMyPlayer = new global::System.Collections.Generic.List<ActionData.LCameraBackToMyPlayer>();
    [global::ProtoBuf.ProtoMember(26, Name=@"CameraBackToMyPlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCameraBackToMyPlayer> CameraBackToMyPlayer
    {
      get { return _CameraBackToMyPlayer; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LCameraBackToCharacter> _CameraBackToCharacter = new global::System.Collections.Generic.List<ActionData.LCameraBackToCharacter>();
    [global::ProtoBuf.ProtoMember(27, Name=@"CameraBackToCharacter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCameraBackToCharacter> CameraBackToCharacter
    {
      get { return _CameraBackToCharacter; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LMoveToNearTarget> _MoveToNearTarget = new global::System.Collections.Generic.List<ActionData.LMoveToNearTarget>();
    [global::ProtoBuf.ProtoMember(28, Name=@"MoveToNearTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LMoveToNearTarget> MoveToNearTarget
    {
      get { return _MoveToNearTarget; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LFaceToNearTarget> _FaceToNearTarget = new global::System.Collections.Generic.List<ActionData.LFaceToNearTarget>();
    [global::ProtoBuf.ProtoMember(29, Name=@"FaceToNearTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LFaceToNearTarget> FaceToNearTarget
    {
      get { return _FaceToNearTarget; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeGravity> _ChangeGravity = new global::System.Collections.Generic.List<ActionData.LChangeGravity>();
    [global::ProtoBuf.ProtoMember(30, Name=@"ChangeGravity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeGravity> ChangeGravity
    {
      get { return _ChangeGravity; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddSoundEvent> _AddSoundEvent = new global::System.Collections.Generic.List<ActionData.LAddSoundEvent>();
    [global::ProtoBuf.ProtoMember(31, Name=@"AddSoundEvent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddSoundEvent> AddSoundEvent
    {
      get { return _AddSoundEvent; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddRandomSoundEvent> _AddRandomSoundEvent = new global::System.Collections.Generic.List<ActionData.LAddRandomSoundEvent>();
    [global::ProtoBuf.ProtoMember(32, Name=@"AddRandomSoundEvent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddRandomSoundEvent> AddRandomSoundEvent
    {
      get { return _AddRandomSoundEvent; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddShock> _AddShock = new global::System.Collections.Generic.List<ActionData.LAddShock>();
    [global::ProtoBuf.ProtoMember(33, Name=@"AddShock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddShock> AddShock
    {
      get { return _AddShock; }
    }
  
    private ActionData.LActionBaseInfo _ActionData;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"ActionData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ActionData.LActionBaseInfo ActionData
    {
      get { return _ActionData; }
      set { _ActionData = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionData.LAddComboRespond> _AddComboRespond = new global::System.Collections.Generic.List<ActionData.LAddComboRespond>();
    [global::ProtoBuf.ProtoMember(35, Name=@"AddComboRespond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddComboRespond> AddComboRespond
    {
      get { return _AddComboRespond; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LTeleport> _Teleport = new global::System.Collections.Generic.List<ActionData.LTeleport>();
    [global::ProtoBuf.ProtoMember(36, Name=@"Teleport", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LTeleport> Teleport
    {
      get { return _Teleport; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LSummonCharacter> _SummonCharacter = new global::System.Collections.Generic.List<ActionData.LSummonCharacter>();
    [global::ProtoBuf.ProtoMember(37, Name=@"SummonCharacter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LSummonCharacter> SummonCharacter
    {
      get { return _SummonCharacter; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LDestroyMe> _DestroyMe = new global::System.Collections.Generic.List<ActionData.LDestroyMe>();
    [global::ProtoBuf.ProtoMember(38, Name=@"DestroyMe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LDestroyMe> DestroyMe
    {
      get { return _DestroyMe; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddBuff> _AddBuff = new global::System.Collections.Generic.List<ActionData.LAddBuff>();
    [global::ProtoBuf.ProtoMember(39, Name=@"AddBuff", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddBuff> AddBuff
    {
      get { return _AddBuff; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LConditionsLinker> _ConditionsLinker = new global::System.Collections.Generic.List<ActionData.LConditionsLinker>();
    [global::ProtoBuf.ProtoMember(40, Name=@"ConditionsLinker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LConditionsLinker> ConditionsLinker
    {
      get { return _ConditionsLinker; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LConditionsLinkerDuration> _ConditionsLinkerDuration = new global::System.Collections.Generic.List<ActionData.LConditionsLinkerDuration>();
    [global::ProtoBuf.ProtoMember(41, Name=@"ConditionsLinkerDuration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LConditionsLinkerDuration> ConditionsLinkerDuration
    {
      get { return _ConditionsLinkerDuration; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeCamp> _ChangeCamp = new global::System.Collections.Generic.List<ActionData.LChangeCamp>();
    [global::ProtoBuf.ProtoMember(42, Name=@"ChangeCamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeCamp> ChangeCamp
    {
      get { return _ChangeCamp; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddSkillCollider> _AddSkillCollider = new global::System.Collections.Generic.List<ActionData.LAddSkillCollider>();
    [global::ProtoBuf.ProtoMember(43, Name=@"AddSkillCollider", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddSkillCollider> AddSkillCollider
    {
      get { return _AddSkillCollider; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LTransfiguration> _Transfiguration = new global::System.Collections.Generic.List<ActionData.LTransfiguration>();
    [global::ProtoBuf.ProtoMember(45, Name=@"Transfiguration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LTransfiguration> Transfiguration
    {
      get { return _Transfiguration; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeBehaviorType> _ChangeBehaviorType = new global::System.Collections.Generic.List<ActionData.LChangeBehaviorType>();
    [global::ProtoBuf.ProtoMember(46, Name=@"ChangeBehaviorType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeBehaviorType> ChangeBehaviorType
    {
      get { return _ChangeBehaviorType; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LJumpToTarget> _JumpToTarget = new global::System.Collections.Generic.List<ActionData.LJumpToTarget>();
    [global::ProtoBuf.ProtoMember(47, Name=@"JumpToTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LJumpToTarget> JumpToTarget
    {
      get { return _JumpToTarget; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LMarkTarget> _MarkTarget = new global::System.Collections.Generic.List<ActionData.LMarkTarget>();
    [global::ProtoBuf.ProtoMember(48, Name=@"MarkTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LMarkTarget> MarkTarget
    {
      get { return _MarkTarget; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LResetActionState> _ResetActionState = new global::System.Collections.Generic.List<ActionData.LResetActionState>();
    [global::ProtoBuf.ProtoMember(49, Name=@"ResetActionState", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LResetActionState> ResetActionState
    {
      get { return _ResetActionState; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LInvincible> _Invincible = new global::System.Collections.Generic.List<ActionData.LInvincible>();
    [global::ProtoBuf.ProtoMember(50, Name=@"Invincible", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LInvincible> Invincible
    {
      get { return _Invincible; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LClearComboCatch> _ClearComboCatch = new global::System.Collections.Generic.List<ActionData.LClearComboCatch>();
    [global::ProtoBuf.ProtoMember(51, Name=@"ClearComboCatch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LClearComboCatch> ClearComboCatch
    {
      get { return _ClearComboCatch; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddForceField> _AddForceField = new global::System.Collections.Generic.List<ActionData.LAddForceField>();
    [global::ProtoBuf.ProtoMember(52, Name=@"AddForceField", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddForceField> AddForceField
    {
      get { return _AddForceField; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeAnimationSpeed> _ChangeAnimationSpeed = new global::System.Collections.Generic.List<ActionData.LChangeAnimationSpeed>();
    [global::ProtoBuf.ProtoMember(53, Name=@"ChangeAnimationSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeAnimationSpeed> ChangeAnimationSpeed
    {
      get { return _ChangeAnimationSpeed; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LEventData> _EventList = new global::System.Collections.Generic.List<ActionData.LEventData>();
    [global::ProtoBuf.ProtoMember(54, Name=@"EventList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LEventData> EventList
    {
      get { return _EventList; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeBodyDirection> _ChangeBodyDirection = new global::System.Collections.Generic.List<ActionData.LChangeBodyDirection>();
    [global::ProtoBuf.ProtoMember(55, Name=@"ChangeBodyDirection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeBodyDirection> ChangeBodyDirection
    {
      get { return _ChangeBodyDirection; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LShakeCamera> _ShakeCamera = new global::System.Collections.Generic.List<ActionData.LShakeCamera>();
    [global::ProtoBuf.ProtoMember(56, Name=@"ShakeCamera", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LShakeCamera> ShakeCamera
    {
      get { return _ShakeCamera; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddSceneEffect> _AddSceneEffect = new global::System.Collections.Generic.List<ActionData.LAddSceneEffect>();
    [global::ProtoBuf.ProtoMember(57, Name=@"AddSceneEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddSceneEffect> AddSceneEffect
    {
      get { return _AddSceneEffect; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LModifyCamera> _ModifyCamera = new global::System.Collections.Generic.List<ActionData.LModifyCamera>();
    [global::ProtoBuf.ProtoMember(58, Name=@"ModifyCamera", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LModifyCamera> ModifyCamera
    {
      get { return _ModifyCamera; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LResetCamera> _ResetCamera = new global::System.Collections.Generic.List<ActionData.LResetCamera>();
    [global::ProtoBuf.ProtoMember(59, Name=@"ResetCamera", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LResetCamera> ResetCamera
    {
      get { return _ResetCamera; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LSwitchModel> _SwitchModel = new global::System.Collections.Generic.List<ActionData.LSwitchModel>();
    [global::ProtoBuf.ProtoMember(60, Name=@"SwitchModel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LSwitchModel> SwitchModel
    {
      get { return _SwitchModel; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LRandomToAction> _RandomToAction = new global::System.Collections.Generic.List<ActionData.LRandomToAction>();
    [global::ProtoBuf.ProtoMember(61, Name=@"RandomToAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LRandomToAction> RandomToAction
    {
      get { return _RandomToAction; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeStance> _ChangeStance = new global::System.Collections.Generic.List<ActionData.LChangeStance>();
    [global::ProtoBuf.ProtoMember(62, Name=@"ChangeStance", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeStance> ChangeStance
    {
      get { return _ChangeStance; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LCheckKeyState> _CheckKeyState = new global::System.Collections.Generic.List<ActionData.LCheckKeyState>();
    [global::ProtoBuf.ProtoMember(63, Name=@"CheckKeyState", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LCheckKeyState> CheckKeyState
    {
      get { return _CheckKeyState; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LFindTarget> _FindTarget = new global::System.Collections.Generic.List<ActionData.LFindTarget>();
    [global::ProtoBuf.ProtoMember(64, Name=@"FindTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LFindTarget> FindTarget
    {
      get { return _FindTarget; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LTargetOperation> _TargetOperation = new global::System.Collections.Generic.List<ActionData.LTargetOperation>();
    [global::ProtoBuf.ProtoMember(65, Name=@"TargetOperation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LTargetOperation> TargetOperation
    {
      get { return _TargetOperation; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LModifyCharacterView> _ModifyCharacterView = new global::System.Collections.Generic.List<ActionData.LModifyCharacterView>();
    [global::ProtoBuf.ProtoMember(66, Name=@"ModifyCharacterView", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LModifyCharacterView> ModifyCharacterView
    {
      get { return _ModifyCharacterView; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LDestroyTarget> _DestroyTarget = new global::System.Collections.Generic.List<ActionData.LDestroyTarget>();
    [global::ProtoBuf.ProtoMember(67, Name=@"DestroyTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LDestroyTarget> DestroyTarget
    {
      get { return _DestroyTarget; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LSetValue> _SetValue = new global::System.Collections.Generic.List<ActionData.LSetValue>();
    [global::ProtoBuf.ProtoMember(68, Name=@"SetValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LSetValue> SetValue
    {
      get { return _SetValue; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LGenericSwitcher> _GenericSwitcher = new global::System.Collections.Generic.List<ActionData.LGenericSwitcher>();
    [global::ProtoBuf.ProtoMember(69, Name=@"GenericSwitcher", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LGenericSwitcher> GenericSwitcher
    {
      get { return _GenericSwitcher; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LTimeStop> _TimeStop = new global::System.Collections.Generic.List<ActionData.LTimeStop>();
    [global::ProtoBuf.ProtoMember(70, Name=@"TimeStop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LTimeStop> TimeStop
    {
      get { return _TimeStop; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddBlur> _AddBlur = new global::System.Collections.Generic.List<ActionData.LAddBlur>();
    [global::ProtoBuf.ProtoMember(71, Name=@"AddBlur", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddBlur> AddBlur
    {
      get { return _AddBlur; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddPhantom> _AddPhantom = new global::System.Collections.Generic.List<ActionData.LAddPhantom>();
    [global::ProtoBuf.ProtoMember(72, Name=@"AddPhantom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddPhantom> AddPhantom
    {
      get { return _AddPhantom; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LRemovePhantom> _RemovePhantom = new global::System.Collections.Generic.List<ActionData.LRemovePhantom>();
    [global::ProtoBuf.ProtoMember(73, Name=@"RemovePhantom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LRemovePhantom> RemovePhantom
    {
      get { return _RemovePhantom; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LVectorAssociateDuration> _VectorAssociateDuration = new global::System.Collections.Generic.List<ActionData.LVectorAssociateDuration>();
    [global::ProtoBuf.ProtoMember(74, Name=@"VectorAssociateDuration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LVectorAssociateDuration> VectorAssociateDuration
    {
      get { return _VectorAssociateDuration; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddColorSeparation> _AddColorSeparation = new global::System.Collections.Generic.List<ActionData.LAddColorSeparation>();
    [global::ProtoBuf.ProtoMember(75, Name=@"AddColorSeparation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddColorSeparation> AddColorSeparation
    {
      get { return _AddColorSeparation; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddGodRay> _AddGodRay = new global::System.Collections.Generic.List<ActionData.LAddGodRay>();
    [global::ProtoBuf.ProtoMember(76, Name=@"AddGodRay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddGodRay> AddGodRay
    {
      get { return _AddGodRay; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddRadialblur> _AddRadialblur = new global::System.Collections.Generic.List<ActionData.LAddRadialblur>();
    [global::ProtoBuf.ProtoMember(77, Name=@"AddRadialblur", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddRadialblur> AddRadialblur
    {
      get { return _AddRadialblur; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LAddJoystickRespond> _AddJoystickRespond = new global::System.Collections.Generic.List<ActionData.LAddJoystickRespond>();
    [global::ProtoBuf.ProtoMember(78, Name=@"AddJoystickRespond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LAddJoystickRespond> AddJoystickRespond
    {
      get { return _AddJoystickRespond; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LMoveByJoystickDuration> _MoveByJoystickDuration = new global::System.Collections.Generic.List<ActionData.LMoveByJoystickDuration>();
    [global::ProtoBuf.ProtoMember(79, Name=@"MoveByJoystickDuration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LMoveByJoystickDuration> MoveByJoystickDuration
    {
      get { return _MoveByJoystickDuration; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeTimeScale> _ChangeTimeScale = new global::System.Collections.Generic.List<ActionData.LChangeTimeScale>();
    [global::ProtoBuf.ProtoMember(80, Name=@"ChangeTimeScale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeTimeScale> ChangeTimeScale
    {
      get { return _ChangeTimeScale; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LModifyUIVisible> _ModifyUIVisible = new global::System.Collections.Generic.List<ActionData.LModifyUIVisible>();
    [global::ProtoBuf.ProtoMember(81, Name=@"ModifyUIVisible", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LModifyUIVisible> ModifyUIVisible
    {
      get { return _ModifyUIVisible; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LSendEvent> _SendEvent = new global::System.Collections.Generic.List<ActionData.LSendEvent>();
    [global::ProtoBuf.ProtoMember(82, Name=@"SendEvent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LSendEvent> SendEvent
    {
      get { return _SendEvent; }
    }
  
    private readonly global::System.Collections.Generic.List<ActionData.LChangeActionSpeed> _ChangeActionSpeed = new global::System.Collections.Generic.List<ActionData.LChangeActionSpeed>();
    [global::ProtoBuf.ProtoMember(83, Name=@"ChangeActionSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionData.LChangeActionSpeed> ChangeActionSpeed
    {
      get { return _ChangeActionSpeed; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}