// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace yd_fieldoptions {
  
  
  #region Enums
  public enum message_field_type {
    E_FIELDTYPE_NORMAL = 1,
    E_FIELDTYPE_PRIMARYKEY = 2,
    E_FIELDTYPE_INDEX = 3,
  }
  
  #endregion
  
}

#endregion Designer generated code
